export default function Slide65AudienceInsights() {
  return (
    <div className="w-screen h-screen overflow-hidden relative bg-[#0a0a14] text-slate-100 font-body">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_bottom_right,rgba(236,72,153,0.18),transparent_55%)]" />
      <div className="absolute top-0 left-0 right-0 h-[6vh] flex items-center justify-between px-[5vw]"><div className="flex items-center gap-[0.7vw]"><div className="h-[1.4vw] w-[1.4vw] rounded-md bg-gradient-to-br from-violet-500 to-fuchsia-500" /><span className="font-display text-[1.2vw] font-bold tracking-tight">1INME</span></div><span className="text-[0.95vw] uppercase tracking-[0.25em] text-slate-400">Audience insights</span></div>

      <div className="relative h-full w-full px-[7vw] pt-[12vh] pb-[8vh] flex flex-col">
        <h2 className="font-display text-[3.4vw] font-bold leading-[1.02] tracking-tight max-w-[55vw]">Know who&rsquo;s on the other side of the click.</h2>

        <div className="mt-[4vh] grid grid-cols-12 gap-[1.5vw] flex-1">
          <div className="col-span-4 rounded-2xl border border-white/10 bg-white/[0.04] p-[1.6vw] flex flex-col"><div className="text-[1vw] uppercase tracking-[0.25em] text-violet-300">Top countries</div><div className="mt-[1.5vh] flex flex-col gap-[1vh]"><div><div className="flex justify-between text-[1.05vw]"><span>United States</span><span className="text-slate-400">41%</span></div><div className="mt-[0.4vh] h-[0.7vh] bg-white/10 rounded-full"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-400 rounded-full" style={{width:'41%'}} /></div></div><div><div className="flex justify-between text-[1.05vw]"><span>Brazil</span><span className="text-slate-400">17%</span></div><div className="mt-[0.4vh] h-[0.7vh] bg-white/10 rounded-full"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-400 rounded-full" style={{width:'17%'}} /></div></div><div><div className="flex justify-between text-[1.05vw]"><span>Germany</span><span className="text-slate-400">12%</span></div><div className="mt-[0.4vh] h-[0.7vh] bg-white/10 rounded-full"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-400 rounded-full" style={{width:'12%'}} /></div></div><div><div className="flex justify-between text-[1.05vw]"><span>Japan</span><span className="text-slate-400">9%</span></div><div className="mt-[0.4vh] h-[0.7vh] bg-white/10 rounded-full"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-400 rounded-full" style={{width:'9%'}} /></div></div><div><div className="flex justify-between text-[1.05vw]"><span>Other</span><span className="text-slate-400">21%</span></div><div className="mt-[0.4vh] h-[0.7vh] bg-white/10 rounded-full"><div className="h-full bg-gradient-to-r from-violet-400 to-fuchsia-400 rounded-full" style={{width:'21%'}} /></div></div></div></div>
          <div className="col-span-4 rounded-2xl border border-white/10 bg-white/[0.04] p-[1.6vw] flex flex-col"><div className="text-[1vw] uppercase tracking-[0.25em] text-fuchsia-300">Devices</div><div className="mt-[1.5vh] grid grid-cols-3 gap-[0.8vw] flex-1 items-end"><div><div className="h-[60%] w-full rounded-t bg-gradient-to-t from-fuchsia-500/30 to-fuchsia-300" /><div className="text-[1vw] mt-[0.5vh] text-center">iOS <span className="text-slate-400">62%</span></div></div><div><div className="h-[28%] w-full rounded-t bg-gradient-to-t from-violet-500/30 to-violet-300" /><div className="text-[1vw] mt-[0.5vh] text-center">Android <span className="text-slate-400">26%</span></div></div><div><div className="h-[12%] w-full rounded-t bg-gradient-to-t from-cyan-500/30 to-cyan-300" /><div className="text-[1vw] mt-[0.5vh] text-center">Desktop <span className="text-slate-400">12%</span></div></div></div></div>
          <div className="col-span-4 rounded-2xl border border-white/10 bg-white/[0.04] p-[1.6vw] flex flex-col"><div className="text-[1vw] uppercase tracking-[0.25em] text-cyan-300">Sources</div><div className="mt-[1.5vh] flex flex-col gap-[1vh] text-[1.1vw]"><div className="flex justify-between"><span>Instagram</span><span className="text-slate-400">38%</span></div><div className="flex justify-between"><span>TikTok</span><span className="text-slate-400">22%</span></div><div className="flex justify-between"><span>Direct</span><span className="text-slate-400">17%</span></div><div className="flex justify-between"><span>YouTube</span><span className="text-slate-400">11%</span></div><div className="flex justify-between"><span>Search</span><span className="text-slate-400">8%</span></div></div></div>
        </div>
      </div>
      <div className="absolute bottom-[3vh] left-[5vw] right-[5vw] flex items-center justify-between text-[0.9vw] text-slate-500"><span>1inme.com</span><span>65 / 84</span></div>
    </div>
  );
}
