<?php

namespace Database\Seeders;

use App\Modules\Admin\Models\BgTemplate;
use App\Modules\Admin\Models\PageTemplate;
use App\Modules\User\Services\PersonaCatalog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Ensures every persona has at least 10 active page templates so the
 * onboarding "Recommended for you" shelf is populated for everyone.
 *
 * Idempotent: a persona that already has >= 10 active templates tagged
 * with that slug in `recommended_personas` is skipped entirely so admin
 * curation isn't clobbered. Templates are also keyed by a stable slug
 * (`persona-<slug>-<variant>`) so re-running this seeder never overwrites
 * an existing row.
 *
 * Each variant rotates through a bank of theme presets so a persona's
 * shelf shows a real spread of looks (animated backgrounds, gradients,
 * photo, light/dark solids) and block mixes (countdown, image_grid,
 * video, testimonials, service, price, cta_button, contact_form, poll,
 * qr_code, card, review, donation, coupon, etc.) — not ten variations
 * of the same beige starter page.
 */
class ExpandedPageTemplateLibrarySeeder extends Seeder
{
    private const MIN_PER_PERSONA = 10;

    /**
     * Blueprint version stamped into every seeded row's
     * `snapshot.meta.seed_version`. Bump this whenever the blueprints in
     * `blueprintsFor()` or `themePresets()` change so the next deploy
     * auto-refreshes untouched persona rows that were generated by an
     * older blueprint version. Admin-edited rows are still preserved
     * (same `updated_at` heuristic as `RefreshPersonaSeed`).
     *
     * IMPORTANT: keep blueprint `key` values stable across redesigns.
     * The auto-refresh in `autoRefreshStaleVersions()` matches stale
     * rows by their `persona-<slug>-<key>` slug — if a redesign renames
     * a blueprint `key`, old rows at the previous slug fall into the
     * "unknown slug — admin-added" bucket and are deliberately left
     * alone. Redesign block contents/copy/themes freely; rename the
     * `key` only when you also intend to retire the old slug.
     */
    public const SEED_VERSION = 1;

    /** Tolerance (seconds) for treating updated_at == created_at. */
    private const EDIT_DRIFT_TOLERANCE = 2;

    /** @var array<string,int|null>|null Cached slug => bg_template id map. */
    private ?array $bgTemplateMap = null;

    public function run(): void
    {
        // Auto-refresh: drop untouched seeded rows whose stored
        // seed_version is older than the current SEED_VERSION so the
        // next deploy after a blueprint redesign rolls forward without
        // anyone having to invoke `templates:refresh-persona-seed`.
        // The fill loop below recreates them with the new design.
        $this->autoRefreshStaleVersions();

        $countsBySlug = [];
        PageTemplate::query()->where('is_active', true)->get(['recommended_personas'])->each(function ($t) use (&$countsBySlug) {
            foreach ((array) ($t->recommended_personas ?? []) as $slug) {
                $countsBySlug[$slug] = ($countsBySlug[$slug] ?? 0) + 1;
            }
        });

        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];
            $have = $countsBySlug[$slug] ?? 0;
            if ($have >= self::MIN_PER_PERSONA) {
                continue;
            }

            $blueprints = $this->blueprintsFor($persona);
            $needed = self::MIN_PER_PERSONA - $have;
            $created = 0;

            foreach ($blueprints as $i => $bp) {
                if ($created >= $needed) break;
                $tplSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);

                if (PageTemplate::where('slug', $tplSlug)->exists()) {
                    continue;
                }

                $this->createBlueprintRow($slug, $bp, $i);
                $created++;
            }
        }
    }

    /**
     * Build the 10 blueprint variants for a persona. Variant `key`s are
     * stable so the resulting slug `persona-<slug>-<key>` stays identical
     * across re-runs (idempotent).
     *
     * @return array<int, array{key:string,name:string,description:string,thumb:string,snapshot:array}>
     */
    public function blueprintsFor(array $persona): array
    {
        $label = $persona['label'];
        $blurb = $persona['blurb'] ?? 'Welcome to my page.';
        $slug = $persona['slug'];

        $thumb = fn(string $variant) => "https://picsum.photos/seed/tpl-{$slug}-{$variant}/600/400";
        $img = fn(string $key, int $n = 1, int $w = 600, int $h = 400) => "https://picsum.photos/seed/{$slug}-{$key}-{$n}/{$w}/{$h}";

        $presets = $this->themePresets();
        $pick = fn(int $i) => $presets[$i % count($presets)];

        return [
            // 0 — Aurora animated bg, profile + featured links
            [
                'key' => 'starter',
                'name' => "{$label} — Aurora Starter",
                'description' => "Animated aurora background with profile, top links, and socials.",
                'thumb' => $thumb('starter'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 1, 200, 200)),
                    $this->heading('My Links', 'h3'),
                    $this->ctaButton('🔥 Featured this week', 'https://example.com', '#7c3aed', '#ffffff'),
                    $this->link('Website', 'https://example.com', 'fa-globe'),
                    $this->link('Latest project', 'https://example.com', 'fa-bookmark'),
                    $this->link('Press kit', 'https://example.com', 'fa-file-lines'),
                    $this->review('Jordan K.', 5, "Their work speaks for itself — instant fan.", $img('rev', 0, 80, 80)),
                    $this->socials(),
                ], $pick(0)),
            ],
            // 1 — Mesh gradient, big featured links + countdown
            [
                'key' => 'links-stack',
                'name' => "{$label} — Featured Links",
                'description' => "Bold gradient with featured buttons and a launch countdown.",
                'thumb' => $thumb('links'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 2, 200, 200)),
                    $this->countdown('Launch in', '+30 days'),
                    $this->linkBig("What I'm working on now", 'https://example.com', 'fa-rocket'),
                    $this->linkBig('Latest update', 'https://example.com', 'fa-newspaper'),
                    $this->ctaButton('👉 Get the goods', 'https://example.com', '#ec4899', '#ffffff'),
                    $this->socials(),
                ], $pick(1)),
            ],
            // 2 — Pastel paper, about + cta + review
            [
                'key' => 'about-cta',
                'name' => "{$label} — About + CTA",
                'description' => "Soft paper look with about-me, a focused CTA, and one glowing review.",
                'thumb' => $thumb('about'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 3, 200, 200)),
                    $this->heading('About me', 'h3'),
                    $this->paragraph("I'm a {$label}. {$blurb}"),
                    $this->divider(),
                    $this->review('Sam P.', 5, "Working with them was the highlight of our quarter — couldn't recommend more.", $img('rev', 1, 80, 80)),
                    $this->ctaButton('Work with me', 'https://example.com', '#0ea5e9', '#ffffff'),
                    $this->socials(),
                ], $pick(2)),
            ],
            // 3 — Mono dark, newsletter + poll
            [
                'key' => 'newsletter',
                'name' => "{$label} — Newsletter",
                'description' => "Sharp mono-dark layout that leads with email signup and a quick poll.",
                'thumb' => $thumb('news'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 4, 200, 200)),
                    $this->heading('Get updates from me', 'h3'),
                    $this->paragraph('One short note when there is something new. No spam.'),
                    $this->emailCollector(),
                    $this->poll('What should I cover next?', ['Behind the scenes', 'Tutorials', 'Q&A', 'Case studies']),
                    $this->socials(),
                ], $pick(3)),
            ],
            // 4 — Photo editorial bg, gallery + image grid
            [
                'key' => 'gallery',
                'name' => "{$label} — Gallery",
                'description' => "Editorial photo background, six-shot portfolio grid, and inquiry CTA.",
                'thumb' => $thumb('gallery'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 5, 200, 200)),
                    $this->heading('Portfolio', 'h3'),
                    $this->imageGrid([
                        $img('grid', 1, 400, 400),
                        $img('grid', 2, 400, 400),
                        $img('grid', 3, 400, 400),
                        $img('grid', 4, 400, 400),
                        $img('grid', 5, 400, 400),
                        $img('grid', 6, 400, 400),
                    ], 3),
                    $this->ctaButton('Inquire about my work', 'https://example.com', '#f59e0b', '#0f172a'),
                    $this->socials(),
                ], $pick(4)),
            ],
            // 5 — Neon cyber, services + price
            [
                'key' => 'services',
                'name' => "{$label} — Services & Pricing",
                'description' => "Neon-cyber backdrop with service cards, a pricing tier, and booking.",
                'thumb' => $thumb('services'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 6, 200, 200)),
                    $this->heading('What I offer', 'h3'),
                    $this->service('1:1 Consultation', 'fa-comments', 'from $120 / hr', 'A focused 60-minute working session — bring your toughest question.', 'https://example.com'),
                    $this->service('Starter Package', 'fa-bolt', '$450', "Get up and running fast. Includes setup, walkthrough, and a follow-up.", 'https://example.com'),
                    $this->price('Pro Engagement', '$1,800', '/ project', [
                        'Discovery + audit',
                        'Hands-on implementation',
                        'Two weeks of async support',
                        'Wrap-up review call',
                    ], 'https://example.com'),
                    $this->ctaButton('Book a call', 'https://example.com', '#a855f7', '#ffffff'),
                    $this->socials(),
                ], $pick(5)),
            ],
            // 6 — Ocean gradient, testimonials + review
            [
                'key' => 'testimonials',
                'name' => "{$label} — Social Proof",
                'description' => "Calm ocean palette stacked with three testimonials and a featured review.",
                'thumb' => $thumb('proof'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 7, 200, 200)),
                    $this->heading('What people say', 'h3'),
                    $this->testimonials([
                        ['name' => 'Alex R.',    'avatar' => $img('t', 1, 80, 80), 'rating' => 5, 'text' => "Genuinely a delight to work with. Recommend without hesitation."],
                        ['name' => 'Priya S.',   'avatar' => $img('t', 2, 80, 80), 'rating' => 5, 'text' => "Made a real difference for our team. Wish we'd started sooner."],
                        ['name' => 'Marcus L.',  'avatar' => $img('t', 3, 80, 80), 'rating' => 4, 'text' => "Sharp eye, clear communication, on time. What more do you want?"],
                    ]),
                    $this->ctaButton('See more reviews', 'https://example.com', '#06b6d4', '#001018'),
                    $this->socials(),
                ], $pick(6)),
            ],
            // 7 — Smoke fog, contact form + vcard + qr
            [
                'key' => 'contact',
                'name' => "{$label} — Contact Hub",
                'description' => "Moody smoke background, contact form, vCard download, and a scan-me QR.",
                'thumb' => $thumb('contact'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 8, 200, 200)),
                    $this->heading('Get in touch', 'h3'),
                    $this->contactForm('Send a message', 'Send'),
                    $this->vcard('Your Name', $label, 'Your Company', '+10000000000', 'hi@example.com', 'https://example.com'),
                    $this->qrCode('https://example.com', 220),
                    $this->socials(),
                ], $pick(7)),
            ],
            // 8 — Prism light, feature image + video + donation
            [
                'key' => 'feature',
                'name' => "{$label} — Feature Story",
                'description' => "Prism-light hero image and short video with a tip-jar donation block.",
                'thumb' => $thumb('feature'),
                'snapshot' => $this->snapshot([
                    $this->image($img('hero', 1, 1200, 600)),
                    $this->heading($label, 'h2'),
                    $this->paragraph($blurb),
                    $this->video('https://download.samplelib.com/mp4/sample-5s.mp4'),
                    $this->donation('Support my work', 'Every tip helps me keep going — thank you.', [5, 10, 25, 50], 'https://example.com'),
                    $this->ctaButton('Learn more', 'https://example.com', '#10b981', '#ffffff'),
                    $this->socials(),
                ], $pick(8)),
            ],
            // 9 — Deep ocean, faq + coupon + card grid
            [
                'key' => 'faq-contact',
                'name' => "{$label} — FAQ + Promo",
                'description' => "Deep-ocean palette: FAQ list, a launch coupon, and a quick-link card grid.",
                'thumb' => $thumb('faq'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 9, 200, 200)),
                    $this->heading('Frequently asked', 'h3'),
                    $this->list([
                        "How do we start? — Drop me a message and we'll set up a quick intro.",
                        'How much does it cost? — Depends on scope; I share a range upfront.',
                        'How fast can we start? — Usually within a week or two.',
                    ]),
                    $this->coupon('WELCOME15', 'Save 15% on your first booking.', 'Dec 31, 2026'),
                    $this->cardGrid('Quick links', 2, [
                        $this->link('Email me', 'mailto:hi@example.com', 'fa-envelope'),
                        $this->link('Book a slot', 'https://example.com', 'fa-calendar'),
                        $this->link('WhatsApp', 'https://wa.me/10000000000', 'fa-whatsapp'),
                        $this->link('Press kit', 'https://example.com', 'fa-file-lines'),
                    ]),
                    $this->ctaButton('Send me a message', 'https://example.com', '#7c3aed', '#ffffff'),
                    $this->socials(),
                ], $pick(9)),
            ],
        ];
    }

    /* ──────────────────────── theme presets ──────────────────────── */

    /**
     * Return the bank of biolink theme presets. Each preset is a settings
     * array merged into the saved snapshot's `biolink` key. Presets cover
     * animated bg-templates, gradients, photo, and solid light/dark looks
     * with matching font/button colors and varied button shapes.
     *
     * @return array<int, array<string, mixed>>
     */
    private function themePresets(): array
    {
        $bg = fn(string $slug): ?int => $this->bgTemplateMap()[$slug] ?? null;

        $presets = [];

        // 0 — Aurora animated
        if ($id = $bg('aurora-borealis')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#7c3aed',
                'font_color'        => '#ffffff',
                'button_color'      => '#7c3aed',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        }

        // 1 — Bold gradient (sunset)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(135deg, #f97316 0%, #ec4899 50%, #8b5cf6 100%)',
            'theme_color'        => '#ec4899',
            'font_color'         => '#ffffff',
            'button_color'       => '#ffffff',
            'button_text_color'  => '#1f2937',
            'button_style'       => 'pill',
        ];

        // 2 — Soft pastel paper (light)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(180deg, #fdf6e3 0%, #fce7f3 100%)',
            'theme_color'        => '#0ea5e9',
            'font_color'         => '#1f2937',
            'button_color'       => '#0ea5e9',
            'button_text_color'  => '#ffffff',
            'button_style'       => 'rounded',
        ];

        // 3 — Mono dark (sharp)
        $presets[] = [
            'background_type'   => 'color',
            'background_color'  => '#0a0a0a',
            'theme_color'       => '#f5f5f5',
            'font_color'        => '#f5f5f5',
            'button_color'      => '#f5f5f5',
            'button_text_color' => '#0a0a0a',
            'button_style'      => 'square',
        ];

        // 4 — Editorial photo
        $presets[] = [
            'background_type'   => 'image',
            'background_image'  => 'https://picsum.photos/seed/tpl-bg-editorial/1200/2000',
            'theme_color'       => '#f59e0b',
            'font_color'        => '#ffffff',
            'button_color'      => '#ffffff',
            'button_text_color' => '#0f172a',
            'button_style'      => 'outline',
        ];

        // 5 — Neon cyber animated (or fallback to neon gradient)
        if ($id = $bg('neon-waves')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#a855f7',
                'font_color'        => '#ffffff',
                'button_color'      => '#a855f7',
                'button_text_color' => '#ffffff',
                'button_style'      => 'shadow',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #0f172a 0%, #581c87 50%, #a855f7 100%)',
                'theme_color'        => '#a855f7',
                'font_color'         => '#ffffff',
                'button_color'       => '#a855f7',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'shadow',
            ];
        }

        // 6 — Ocean gradient (calm)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(160deg, #0c4a6e 0%, #0e7490 60%, #06b6d4 100%)',
            'theme_color'        => '#06b6d4',
            'font_color'         => '#f0fdff',
            'button_color'       => '#06b6d4',
            'button_text_color'  => '#001018',
            'button_style'       => 'pill',
        ];

        // 7 — Smoke fog animated (or moody gradient fallback)
        if ($id = $bg('smoke-fog')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#94a3b8',
                'font_color'        => '#f8fafc',
                'button_color'      => '#1e293b',
                'button_text_color' => '#f8fafc',
                'button_style'      => 'outline',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #1f2937 0%, #374151 100%)',
                'theme_color'        => '#94a3b8',
                'font_color'         => '#f8fafc',
                'button_color'       => '#1e293b',
                'button_text_color'  => '#f8fafc',
                'button_style'       => 'outline',
            ];
        }

        // 8 — Prism light animated (or warm light gradient)
        if ($id = $bg('prism-light')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#10b981',
                'font_color'        => '#ffffff',
                'button_color'      => '#10b981',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #fef3c7 0%, #fbbf24 100%)',
                'theme_color'        => '#10b981',
                'font_color'         => '#1f2937',
                'button_color'       => '#10b981',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'rounded',
            ];
        }

        // 9 — Deep ocean animated (or deep gradient fallback)
        if ($id = $bg('deep-ocean')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#7c3aed',
                'font_color'        => '#e0e7ff',
                'button_color'      => '#7c3aed',
                'button_text_color' => '#ffffff',
                'button_style'      => 'pill',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #020617 0%, #1e1b4b 100%)',
                'theme_color'        => '#7c3aed',
                'font_color'         => '#e0e7ff',
                'button_color'       => '#7c3aed',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'pill',
            ];
        }

        return $presets;
    }

    /** @return array<string,int> */
    private function bgTemplateMap(): array
    {
        if ($this->bgTemplateMap === null) {
            try {
                $this->bgTemplateMap = BgTemplate::query()
                    ->pluck('id', 'slug')
                    ->map(fn($id) => (int) $id)
                    ->all();
            } catch (\Throwable $e) {
                // Table may not exist yet on first boot — degrade gracefully.
                $this->bgTemplateMap = [];
            }
        }
        return $this->bgTemplateMap;
    }

    /* ──────────────────── snapshot + block helpers ──────────────────── */

    private function snapshot(array $blocks, array $biolink = []): array
    {
        // `meta.seed_version` lets a future seeder run detect rows
        // generated by an older blueprint version and auto-refresh them
        // (see `autoRefreshStaleVersions()`). Anything else admins or
        // future blocks want to stash on the snapshot is preserved.
        return [
            'biolink' => $biolink,
            'blocks'  => $blocks,
            'meta'    => ['seed_version' => self::SEED_VERSION],
        ];
    }

    /**
     * Refresh seed-generated persona rows whose stored `seed_version`
     * is older than the current SEED_VERSION. For each persona we walk
     * its current blueprint set and, for any row that:
     *
     *  - lives at a known blueprint slug (admin-added rows in the
     *    `persona-<slug>-*` namespace are skipped — unknown slug),
     *  - has `updated_at` within EDIT_DRIFT_TOLERANCE of `created_at`
     *    (admin edits through the panel are preserved — same heuristic
     *    as `RefreshPersonaSeed`), and
     *  - carries a `meta.seed_version` lower than SEED_VERSION,
     *
     * we delete the stale row and immediately recreate it from the
     * current blueprint targeting the SAME slug. Slug-targeted refresh
     * is required because the count-based fill loop in `run()` only
     * tops personas up to MIN_PER_PERSONA — if a persona already has
     * enough templates (e.g. admin-added ones), the gap-fill would
     * never recreate the deleted slug. Refreshing inline guarantees
     * every untouched, current-blueprint slug ends up at SEED_VERSION
     * regardless of how many other templates the persona carries.
     *
     * Idempotent: once every row is at the current version this method
     * is a true no-op on every subsequent run.
     */
    private function autoRefreshStaleVersions(): void
    {
        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];

            // Build a slug => [blueprint, index] map so we can recreate
            // a refreshed row with the exact same sort_order it had.
            $blueprintBySlug = [];
            foreach ($this->blueprintsFor($persona) as $i => $bp) {
                $bpSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);
                $blueprintBySlug[$bpSlug] = ['bp' => $bp, 'i' => $i];
            }
            if (empty($blueprintBySlug)) {
                continue;
            }

            $rows = PageTemplate::query()
                ->where('slug', 'like', 'persona-' . $slug . '-%')
                ->get(['id', 'slug', 'snapshot', 'created_at', 'updated_at']);

            foreach ($rows as $row) {
                if (!isset($blueprintBySlug[$row->slug])) {
                    continue; // unknown slug — admin-added, leave alone.
                }
                if ($row->updated_at && $row->created_at
                    && $row->updated_at->getTimestamp() - $row->created_at->getTimestamp() > self::EDIT_DRIFT_TOLERANCE) {
                    continue; // admin edited through the panel — preserve.
                }
                $stored = (int) (((array) $row->snapshot)['meta']['seed_version'] ?? 0);
                if ($stored >= self::SEED_VERSION) {
                    continue;
                }

                // Slug-targeted refresh: drop the stale row and rebuild
                // it from the current blueprint at the same slug. We
                // can't rely on the count-based gap-fill below because
                // personas with admin-added rows may already meet
                // MIN_PER_PERSONA and the deleted slug would never come
                // back.
                $entry = $blueprintBySlug[$row->slug];
                PageTemplate::whereKey($row->id)->delete();
                $this->createBlueprintRow($slug, $entry['bp'], $entry['i']);
            }
        }
    }

    /**
     * Insert one persona blueprint row. Shared between the count-based
     * gap-fill (in `run()`) and the per-slug auto-refresh path so both
     * stamp identical fields, including `snapshot.meta.seed_version`.
     *
     * @param  array{key:string,name:string,description:string,thumb:string,snapshot:array}  $bp
     */
    private function createBlueprintRow(string $personaSlug, array $bp, int $index): void
    {
        PageTemplate::create([
            'slug'                 => 'persona-' . $personaSlug . '-' . Str::slug($bp['key']),
            'name'                 => $bp['name'],
            'category'             => $personaSlug,
            'description'          => $bp['description'],
            'thumbnail_url'        => $bp['thumb'],
            'plan_tier'            => null,
            'is_active'            => true,
            'sort_order'           => 100 + $index,
            'recommended_personas' => [$personaSlug],
            'snapshot'             => $bp['snapshot'],
        ]);
    }

    private function block(string $type, array $settings): array
    {
        return ['type' => $type, 'settings' => $settings, 'is_active' => true];
    }

    private function profile(string $label, string $blurb, string $avatar = ''): array
    {
        return $this->block('profile_card_v1', [
            'name'   => 'Your Name',
            'title'  => $label,
            'avatar' => $avatar,
            'bio'    => $blurb,
        ]);
    }

    private function heading(string $text, string $size = 'h3'): array
    {
        return $this->block('heading', ['text' => $text, 'size' => $size, 'align' => 'center']);
    }

    private function paragraph(string $text): array
    {
        return $this->block('paragraph', ['text' => $text, 'align' => 'center']);
    }

    private function link(string $text, string $url, string $icon = ''): array
    {
        return $this->block('link', ['text' => $text, 'url' => $url, 'icon' => $icon]);
    }

    private function linkBig(string $text, string $url, string $icon = ''): array
    {
        return $this->block('link_big', ['text' => $text, 'url' => $url, 'icon' => $icon]);
    }

    private function socials(): array
    {
        // Seed a deterministic set of placeholder platforms so the icon
        // row actually renders in preview. The user replaces these with
        // their own handles after picking the template.
        return $this->block('socials_multi', [
            'groups' => [[
                'label'     => 'Personal',
                'platforms' => [
                    ['name' => 'instagram', 'url' => 'https://instagram.com/yourhandle', 'display' => 'icon'],
                    ['name' => 'tiktok',    'url' => 'https://tiktok.com/@yourhandle',  'display' => 'icon'],
                    ['name' => 'youtube',   'url' => 'https://youtube.com/@yourhandle', 'display' => 'icon'],
                    ['name' => 'twitter',   'url' => 'https://x.com/yourhandle',        'display' => 'icon'],
                    ['name' => 'linkedin',  'url' => 'https://linkedin.com/in/yourhandle', 'display' => 'icon'],
                ],
            ]],
            'size'  => 'md',
            'style' => 'rounded',
        ]);
    }

    private function emailCollector(): array
    {
        return $this->block('email_collector', ['placeholder' => 'you@email.com', 'button_text' => 'Subscribe']);
    }

    private function image(string $url = ''): array
    {
        return $this->block('image', ['url' => $url, 'alt' => '']);
    }

    private function imageGrid(array $images = [], int $columns = 3): array
    {
        return $this->block('image_grid', [
            'columns' => $columns,
            'gap'     => 2,
            'images'  => array_map(fn($u) => ['url' => $u], $images),
        ]);
    }

    private function divider(): array
    {
        return $this->block('divider', []);
    }

    private function list(array $items): array
    {
        return $this->block('list', ['items' => $items]);
    }

    /* ─── new richer blocks ─── */

    private function countdown(string $title, string $relative = '+30 days'): array
    {
        $target = now()->modify($relative)->toIso8601String();
        return $this->block('countdown', ['title' => $title, 'target_date' => $target]);
    }

    private function video(string $url): array
    {
        return $this->block('video', ['url' => $url, 'autoplay' => false]);
    }

    private function testimonials(array $items): array
    {
        return $this->block('testimonials', ['items' => $items]);
    }

    private function review(string $name, int $rating, string $text, string $avatar = ''): array
    {
        return $this->block('review', [
            'name'   => $name,
            'avatar' => $avatar,
            'rating' => $rating,
            'text'   => $text,
        ]);
    }

    private function service(string $name, string $icon, string $price, string $description, string $url): array
    {
        return $this->block('service', [
            'name'        => $name,
            'icon'        => 'fas ' . $icon,
            'price'       => $price,
            'description' => $description,
            'url'         => $url,
        ]);
    }

    private function price(string $title, string $amount, string $period, array $features, string $url): array
    {
        return $this->block('price', [
            'title'    => $title,
            'amount'   => $amount,
            'period'   => $period,
            'features' => $features,
            'url'      => $url,
        ]);
    }

    private function ctaButton(string $text, string $url, string $color = '#7c3aed', string $textColor = '#ffffff', string $size = 'lg'): array
    {
        return $this->block('cta_button', [
            'text'       => $text,
            'url'        => $url,
            'color'      => $color,
            'text_color' => $textColor,
            'size'       => $size,
        ]);
    }

    private function contactForm(string $title, string $buttonText): array
    {
        return $this->block('contact_form', [
            'title'           => $title,
            'button_text'     => $buttonText,
            'success_message' => 'Got it — I\'ll get back to you soon.',
        ]);
    }

    private function poll(string $question, array $options): array
    {
        return $this->block('poll', ['question' => $question, 'options' => array_values($options)]);
    }

    private function qrCode(string $url, int $size = 200): array
    {
        return $this->block('qr_code', ['url' => $url, 'size' => $size]);
    }

    private function donation(string $title, string $description, array $amounts, string $url): array
    {
        return $this->block('donation', [
            'title'       => $title,
            'description' => $description,
            'amounts'     => array_values($amounts),
            'url'         => $url,
        ]);
    }

    private function coupon(string $code, string $description, string $expires): array
    {
        return $this->block('coupon', ['code' => $code, 'description' => $description, 'expires' => $expires]);
    }

    private function vcard(string $name, string $title, string $company, string $phone, string $email, string $website): array
    {
        return $this->block('vcard', [
            'name'    => $name,
            'title'   => $title,
            'company' => $company,
            'phone'   => $phone,
            'email'   => $email,
            'website' => $website,
        ]);
    }

    /**
     * Card container with children — renders a small grid of child blocks
     * inside one styled card. Keeps the variant from devolving back into
     * a plain link list.
     */
    private function cardGrid(string $title, int $columns, array $children): array
    {
        $card = $this->block('card', [
            'title'         => $title,
            'columns'       => $columns,
            'gap'           => 12,
            'padding'       => 16,
            'border_radius' => 16,
            'bg_type'       => 'glass',
            'glass_opacity' => 6,
            'glass_blur'    => 12,
            'shadow'        => 'sm',
        ]);
        $card['children'] = array_values($children);
        return $card;
    }
}
