<?php

namespace Database\Seeders;

use App\Modules\Admin\Models\BgTemplate;
use App\Modules\Admin\Models\PageTemplate;
use App\Modules\User\Models\BiolinkBlock;
use App\Modules\User\Services\PersonaCatalog;
use App\Modules\User\Support\BlockVariantCatalog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Ensures every persona has at least 10 active page templates so the
 * onboarding "Recommended for you" shelf is populated for everyone.
 *
 * Idempotent: a persona that already has >= 10 active templates tagged
 * with that slug in `recommended_personas` is skipped entirely so admin
 * curation isn't clobbered. Templates are also keyed by a stable slug
 * (`persona-<slug>-<variant>`) so re-running this seeder never overwrites
 * an existing row.
 *
 * Each variant rotates through a bank of theme presets so a persona's
 * shelf shows a real spread of looks (animated backgrounds, gradients,
 * photo, light/dark solids) and block mixes (countdown, image_grid,
 * video, testimonials, service, price, cta_button, contact_form, poll,
 * qr_code, card, review, donation, coupon, etc.) — not ten variations
 * of the same beige starter page.
 */
class ExpandedPageTemplateLibrarySeeder extends Seeder
{
    private const MIN_PER_PERSONA = 10;

    /**
     * Blueprint version stamped into every seeded row's
     * `snapshot.meta.seed_version`. Bump this whenever the blueprints in
     * `blueprintsFor()` or `themePresets()` change so the next deploy
     * auto-refreshes untouched persona rows that were generated by an
     * older blueprint version. Admin-edited rows are still preserved
     * (same `updated_at` heuristic as `RefreshPersonaSeed`).
     *
     * IMPORTANT: keep blueprint `key` values stable across redesigns.
     * The auto-refresh in `autoRefreshStaleVersions()` matches stale
     * rows by their `persona-<slug>-<key>` slug — if a redesign renames
     * a blueprint `key`, old rows at the previous slug fall into the
     * "unknown slug — admin-added" bucket and are deliberately left
     * alone. Redesign block contents/copy/themes freely; rename the
     * `key` only when you also intend to retire the old slug.
     */
    public const SEED_VERSION = 3;

    /** Tolerance (seconds) for treating updated_at == created_at. */
    private const EDIT_DRIFT_TOLERANCE = 2;

    /** @var array<string,int|null>|null Cached slug => bg_template id map. */
    private ?array $bgTemplateMap = null;

    public function run(): void
    {
        // Auto-refresh: drop untouched seeded rows whose stored
        // seed_version is older than the current SEED_VERSION so the
        // next deploy after a blueprint redesign rolls forward without
        // anyone having to invoke `templates:refresh-persona-seed`.
        // The fill loop below recreates them with the new design.
        $this->autoRefreshStaleVersions();

        $countsBySlug = [];
        PageTemplate::query()->where('is_active', true)->get(['recommended_personas'])->each(function ($t) use (&$countsBySlug) {
            foreach ((array) ($t->recommended_personas ?? []) as $slug) {
                $countsBySlug[$slug] = ($countsBySlug[$slug] ?? 0) + 1;
            }
        });

        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];
            $have = $countsBySlug[$slug] ?? 0;
            if ($have >= self::MIN_PER_PERSONA) {
                continue;
            }

            $blueprints = $this->blueprintsFor($persona);
            $needed = self::MIN_PER_PERSONA - $have;
            $created = 0;

            foreach ($blueprints as $i => $bp) {
                if ($created >= $needed) break;
                $tplSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);

                if (PageTemplate::where('slug', $tplSlug)->exists()) {
                    continue;
                }

                $this->createBlueprintRow($slug, $bp, $i);
                $created++;
            }
        }
    }

    /**
     * Build the 10 blueprint variants for a persona. Variant `key`s are
     * stable so the resulting slug `persona-<slug>-<key>` stays identical
     * across re-runs (idempotent).
     *
     * @return array<int, array{key:string,name:string,description:string,thumb:string,snapshot:array}>
     */
    public function blueprintsFor(array $persona): array
    {
        $label = $persona['label'];
        $blurb = $persona['blurb'] ?? 'Welcome to my page.';
        $slug = $persona['slug'];

        $thumb = fn(string $variant) => $this->photo($this->personaKeyword($slug), 600, 400, "tpl-{$slug}-{$variant}");
        $img = function (string $key, int $n = 1, int $w = 600, int $h = 400) use ($slug) {
            $seed = "{$slug}-{$key}-{$n}";
            // People shots (profile avatar, review/testimonial faces) use a
            // dedicated realistic-face placeholder so they always read as a
            // real person rather than a random landscape.
            if (in_array($key, ['avatar', 'rev', 't'], true)) {
                return $this->face($seed, $w);
            }
            $keyword = match ($key) {
                'prod'  => 'product,minimal',
                'grid'  => $this->personaKeyword($slug) . ',portfolio',
                default => $this->personaKeyword($slug),
            };
            return $this->photo($keyword, $w, $h, $seed);
        };

        $presets = $this->themePresets();
        $pick = fn(int $i) => $presets[$i % count($presets)];
        $kits = $this->variantKits();
        $kit = fn(int $i) => $kits[$i % count($kits)];

        return [
            // 0 — Aurora glass: profile, intro, FAQ, featured links, review
            [
                'key' => 'starter',
                'name' => "{$label} — Aurora Starter",
                'description' => "Animated aurora background with a glass profile card, a warm intro, a quick FAQ, and your top links.",
                'thumb' => $thumb('starter'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 1, 200, 200), $kit(0), $img('cover', 1, 1200, 480)),
                    $this->badge('✦ Currently taking on new work', '#8b5cf6', '#ffffff'),
                    $this->heading('Start here', 'h3'),
                    $this->paragraph("Hi, I'm a {$label} and this is my corner of the internet. Everything I'm working on, sharing, and recommending lives right here."),
                    $this->paragraph("New here? Skim the quick FAQ below, then pick a link to dive in. Questions are always welcome."),
                    $this->faqV2([
                        ['question' => 'Who are you?', 'answer' => "I'm a {$label}. {$blurb}", 'icon' => 'fa-user'],
                        ['question' => 'What will I find here?', 'answer' => 'My latest work, the easiest ways to reach me, and the things I genuinely recommend.', 'icon' => 'fa-compass'],
                        ['question' => 'How do we work together?', 'answer' => 'Tap a link below or send a note — I read and reply to everyone who reaches out.', 'icon' => 'fa-handshake'],
                    ]),
                    $this->heading('My links', 'h3'),
                    $this->link('Visit my website', 'https://example.com', 'fa-globe', $kit(0)),
                    $this->link('See my latest project', 'https://example.com', 'fa-bookmark', $kit(0)),
                    $this->link('Download my press kit', 'https://example.com', 'fa-file-lines', $kit(0)),
                    $this->review('Jordan K.', 5, "Their work speaks for itself — I was an instant fan and have been recommending them ever since.", $img('rev', 0, 80, 80)),
                    $this->socials(),
                ], $pick(0)),
            ],
            // 1 — Sunset gradient: cover-hero profile, countdown, big links, timeline
            [
                'key' => 'links-stack',
                'name' => "{$label} — Featured Links",
                'description' => "Bold sunset gradient with a cover-hero profile, a launch countdown, big featured buttons, and a milestone timeline.",
                'thumb' => $thumb('links'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 2, 200, 200), $kit(1), $img('cover', 2, 1200, 480)),
                    $this->countdown('Next drop in', '+21 days'),
                    $this->oneTimeOffer('Early-bird access', 'Lock in the launch price before the countdown hits zero — limited spots at this rate.', '$29', '$49', 'https://example.com'),
                    $this->heading('Latest from me', 'h3'),
                    $this->linkBig("What I'm working on now", 'https://example.com', 'fa-rocket', $kit(1)),
                    $this->linkBig('Read the latest update', 'https://example.com', 'fa-newspaper', $kit(1)),
                    $this->linkBig('Join the waitlist', 'https://example.com', 'fa-bell', $kit(1)),
                    $this->timeline([
                        ['title' => 'Where it started', 'description' => 'Began sharing my work publicly and never looked back.', 'date' => '2023'],
                        ['title' => 'A big milestone', 'description' => 'Hit a goal I once thought was years away.', 'date' => '2024'],
                        ['title' => 'What I\'m building now', 'description' => 'The next chapter — follow along below.', 'date' => '2025'],
                    ]),
                    $this->ctaButton('👉 Get the goods', 'https://example.com', '#ec4899', '#ffffff'),
                    $this->socials(),
                ], $pick(1)),
            ],
            // 2 — Pastel paper: classic profile, about, review, CTA
            [
                'key' => 'about-cta',
                'name' => "{$label} — About + CTA",
                'description' => "Soft paper look with a classic profile card, a two-part about-me, a glowing review, and a focused call-to-action.",
                'thumb' => $thumb('about'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 3, 200, 200), $kit(2), $img('cover', 3, 1200, 480)),
                    $this->heading('About me', 'h3'),
                    $this->paragraph("I'm a {$label}. {$blurb}"),
                    $this->paragraph("I care about doing thoughtful work, communicating clearly, and leaving every project better than I found it. If that sounds like a fit, I'd love to hear from you."),
                    $this->progress([
                        ['label' => 'Replies within 24 hours', 'value' => 98, 'color' => '#0ea5e9'],
                        ['label' => 'Projects delivered on time', 'value' => 95, 'color' => '#22c55e'],
                        ['label' => '2026 calendar booked', 'value' => 70, 'color' => '#f59e0b'],
                    ]),
                    $this->divider(),
                    $this->review('Sam P.', 5, "Working with them was the highlight of our quarter — clear, calm, and genuinely great at what they do. Couldn't recommend more.", $img('rev', 1, 80, 80)),
                    $this->ctaButton('Work with me', 'https://example.com', '#0ea5e9', '#ffffff'),
                    $this->socials(),
                ], $pick(2)),
            ],
            // 3 — Mono dark: badge profile, newsletter, poll, quiz
            [
                'key' => 'newsletter',
                'name' => "{$label} — Newsletter",
                'description' => "Sharp mono-dark layout with a badge profile that leads with email signup, a quick poll, and a fun quiz.",
                'thumb' => $thumb('news'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 4, 200, 200), $kit(3), $img('cover', 4, 1200, 480)),
                    $this->heading('Get updates from me', 'h3'),
                    $this->paragraph('One short note when there is something genuinely new. No spam, no noise — and you can leave any time.'),
                    $this->alert('Subscribers get every new piece a full day before it goes public.', 'success', 'fa-circle-check'),
                    $this->emailCollector(),
                    $this->poll('What should I cover next?', ['Behind the scenes', 'Tutorials', 'Q&A sessions', 'Case studies']),
                    $this->quiz('How well do you know my work?', [
                        ['question' => 'What do I help people with most?', 'options' => ['Strategy', 'Hands-on building', 'Both'], 'correct' => 2],
                        ['question' => 'How often do I send updates?', 'options' => ['Daily', 'Only when it matters', 'Never'], 'correct' => 1],
                    ]),
                    $this->socials(),
                ], $pick(3)),
            ],
            // 4 — Editorial photo: magazine profile, gallery, testimonials, product
            [
                'key' => 'gallery',
                'name' => "{$label} — Gallery",
                'description' => "Editorial photo background with a magazine profile, a six-shot portfolio grid, real testimonials, and a featured product.",
                'thumb' => $thumb('gallery'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 5, 200, 200), $kit(4), $img('cover', 5, 1200, 480)),
                    $this->heading('Selected work', 'h3'),
                    $this->imageGrid([
                        $img('grid', 1, 400, 400),
                        $img('grid', 2, 400, 400),
                        $img('grid', 3, 400, 400),
                        $img('grid', 4, 400, 400),
                        $img('grid', 5, 400, 400),
                        $img('grid', 6, 400, 400),
                    ], 3),
                    $this->imageSlider([
                        $img('grid', 7, 1000, 640),
                        $img('grid', 8, 1000, 640),
                        $img('grid', 9, 1000, 640),
                    ]),
                    $this->testimonials([
                        ['name' => 'Dana M.', 'avatar' => $img('t', 4, 80, 80), 'rating' => 5, 'text' => "Every shot in the deck was exactly what we needed. A real eye."],
                        ['name' => 'Leo T.',  'avatar' => $img('t', 5, 80, 80), 'rating' => 5, 'text' => "Turned a vague brief into something we were proud to ship."],
                    ]),
                    $this->product('Signature Print', 'A museum-quality print of one of my favourite pieces, ready to frame.', '$45', $img('prod', 1, 600, 600), 'https://example.com', 'New'),
                    $this->ctaButton('Inquire about my work', 'https://example.com', '#f59e0b', '#0f172a'),
                    $this->socials(),
                ], $pick(4)),
            ],
            // 5 — Neon cyber: stats profile, services, pricing, product
            [
                'key' => 'services',
                'name' => "{$label} — Services & Pricing",
                'description' => "Neon-cyber backdrop with a stats profile, service cards, a pricing tier, and a productised offer.",
                'thumb' => $thumb('services'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 6, 200, 200), $kit(5), $img('cover', 6, 1200, 480)),
                    $this->heading('What I offer', 'h3'),
                    $this->service('1:1 Consultation', 'fa-comments', 'from $120 / hr', 'A focused 60-minute working session — bring your toughest question and leave with a plan.', 'https://example.com'),
                    $this->service('Starter Package', 'fa-bolt', '$450', "Get up and running fast. Includes setup, a guided walkthrough, and a follow-up check-in.", 'https://example.com'),
                    $this->price('Pro Engagement', '$1,800', '/ project', [
                        'Discovery + audit',
                        'Hands-on implementation',
                        'Two weeks of async support',
                        'Wrap-up review call',
                    ], 'https://example.com'),
                    $this->listPricing([
                        ['name' => 'Discovery call', 'price' => 'Free', 'included' => true],
                        ['name' => 'Project roadmap', 'price' => 'Included', 'included' => true],
                        ['name' => 'Async support', 'price' => 'Included', 'included' => true],
                        ['name' => 'Rush turnaround', 'price' => '+$300', 'included' => false],
                    ]),
                    $this->product('Template Pack', 'Everything I use to deliver client work, packaged so you can run it yourself.', '$79', $img('prod', 2, 600, 600), 'https://example.com', 'Popular'),
                    $this->ctaButton('Book a call', 'https://example.com', '#a855f7', '#ffffff'),
                    $this->socials(),
                ], $pick(5)),
            ],
            // 6 — Ocean: split profile, testimonials, review, FAQ
            [
                'key' => 'testimonials',
                'name' => "{$label} — Social Proof",
                'description' => "Calm ocean palette with a split profile, three testimonials, a featured review, and an objection-busting FAQ.",
                'thumb' => $thumb('proof'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 7, 200, 200), $kit(6), $img('cover', 7, 1200, 480)),
                    $this->badge('★ 5.0 average from 120+ clients', '#06b6d4', '#001018'),
                    $this->heading('What people say', 'h3'),
                    $this->testimonials([
                        ['name' => 'Alex R.',    'avatar' => $img('t', 1, 80, 80), 'rating' => 5, 'text' => "Genuinely a delight to work with. Recommend without hesitation."],
                        ['name' => 'Priya S.',   'avatar' => $img('t', 2, 80, 80), 'rating' => 5, 'text' => "Made a real difference for our team. Wish we'd started sooner."],
                        ['name' => 'Marcus L.',  'avatar' => $img('t', 3, 80, 80), 'rating' => 4, 'text' => "Sharp eye, clear communication, on time. What more do you want?"],
                    ]),
                    $this->review('Nadia F.', 5, "Six months on, the work is still paying off. That's the real test, and it passed.", $img('rev', 2, 80, 80)),
                    $this->faqV2([
                        ['question' => 'How do you collect reviews?', 'answer' => 'Every review here comes straight from a real client after we wrap up a project together.', 'icon' => 'fa-star'],
                        ['question' => 'Can I talk to a past client?', 'answer' => 'Absolutely — ask and I\'ll happily connect you with someone whose project is close to yours.', 'icon' => 'fa-comments'],
                    ]),
                    $this->ctaButton('See more reviews', 'https://example.com', '#06b6d4', '#001018'),
                    $this->socials(),
                ], $pick(6)),
            ],
            // 7 — Smoke fog: floating stats profile, contact form, vCard, QR, FAQ
            [
                'key' => 'contact',
                'name' => "{$label} — Contact Hub",
                'description' => "Moody smoke background with a floating profile, a contact form, a vCard download, a scan-me QR, and a short FAQ.",
                'thumb' => $thumb('contact'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 8, 200, 200), $kit(7), $img('cover', 8, 1200, 480)),
                    $this->heading('Get in touch', 'h3'),
                    $this->paragraph('The fastest way to reach me is the form below. Prefer to save my details? Grab the vCard or scan the code.'),
                    $this->contactForm('Send a message', 'Send'),
                    $this->whatsapp('+10000000000', 'Message me on WhatsApp', "Hi! I found you through your page and wanted to get in touch."),
                    $this->vcard('Your Name', $label, 'Your Company', '+10000000000', 'hi@example.com', 'https://example.com'),
                    $this->qrCode('https://example.com', 220),
                    $this->faq([
                        ['question' => 'How soon will you reply?', 'answer' => 'Usually within one business day.'],
                        ['question' => 'What should I include?', 'answer' => 'A sentence or two about what you need and your timeline is plenty to start.'],
                    ]),
                    $this->socials(),
                ], $pick(7)),
            ],
            // 8 — Prism light: feature image, video, timeline, donation
            [
                'key' => 'feature',
                'name' => "{$label} — Feature Story",
                'description' => "Prism-light hero image and short video, a journey timeline, and a tip-jar donation block.",
                'thumb' => $thumb('feature'),
                'snapshot' => $this->snapshot([
                    $this->image($img('hero', 1, 1200, 600)),
                    $this->heading($label, 'h2'),
                    $this->paragraph($blurb),
                    $this->paragraph("Here's the story behind the work — where it came from, where it's going, and how you can be part of it."),
                    $this->video('https://download.samplelib.com/mp4/sample-5s.mp4'),
                    $this->timeline([
                        ['title' => 'The spark', 'description' => 'A small idea that wouldn\'t leave me alone.', 'date' => '2022'],
                        ['title' => 'Going all in', 'description' => 'Made it my full-time focus.', 'date' => '2024'],
                        ['title' => 'Today', 'description' => 'Building in the open and grateful for the support.', 'date' => '2025'],
                    ]),
                    $this->progress([
                        ['label' => 'Monthly support goal', 'value' => 64, 'color' => '#10b981'],
                    ]),
                    $this->donation('Support my work', 'Every tip helps me keep going — thank you for being here.', [5, 10, 25, 50], 'https://example.com'),
                    $this->ctaButton('Learn more', 'https://example.com', '#10b981', '#ffffff'),
                    $this->socials(),
                ], $pick(8)),
            ],
            // 9 — Deep ocean: gradient badge profile, FAQ, coupon, product, card grid
            [
                'key' => 'faq-contact',
                'name' => "{$label} — FAQ + Promo",
                'description' => "Deep-ocean palette with a gradient badge profile, a real FAQ block, a launch coupon, a featured product, and a quick-link card grid.",
                'thumb' => $thumb('faq'),
                'snapshot' => $this->snapshot([
                    $this->profile($label, $blurb, $img('avatar', 9, 200, 200), $kit(9), $img('cover', 9, 1200, 480)),
                    $this->heading('Frequently asked', 'h3'),
                    $this->faqV2([
                        ['question' => 'How do we start?', 'answer' => "Drop me a message and we'll set up a quick intro call to see if it's a fit.", 'icon' => 'fa-flag'],
                        ['question' => 'How much does it cost?', 'answer' => 'It depends on scope, so I always share a clear range upfront — no surprises.', 'icon' => 'fa-tag'],
                        ['question' => 'How fast can we start?', 'answer' => 'Usually within a week or two, depending on the current schedule.', 'icon' => 'fa-bolt'],
                    ]),
                    $this->alert('Only two new project slots left this month — book early to claim one.', 'warning', 'fa-triangle-exclamation'),
                    $this->coupon('WELCOME15', 'Save 15% on your first booking.', 'Dec 31, 2026'),
                    $this->product('Quick-Start Session', 'A single focused session to unblock you — perfect if you just need a push in the right direction.', '$99', $img('prod', 3, 600, 600), 'https://example.com', 'Limited'),
                    $this->cardGrid('Quick links', 2, [
                        $this->link('Email me', 'mailto:hi@example.com', 'fa-envelope'),
                        $this->link('Book a slot', 'https://example.com', 'fa-calendar'),
                        $this->link('WhatsApp', 'https://wa.me/10000000000', 'fa-whatsapp'),
                        $this->link('Press kit', 'https://example.com', 'fa-file-lines'),
                    ]),
                    $this->ctaButton('Send me a message', 'https://example.com', '#7c3aed', '#ffffff'),
                    $this->socials(),
                ], $pick(9)),
            ],
        ];
    }

    /**
     * Per-blueprint "variant kit": the profile block type + identity
     * variant (which carries the `_profile_layout`) plus the link/big-link
     * design variant key used across that template. Indexed in lockstep
     * with the 10 blueprints so each template gets a distinct profile
     * layout AND a distinct link look (on top of its distinct theme
     * preset). Keys reference BlockVariantCatalog::forType() — `find()`
     * tolerates an unknown key (renderer falls back to defaults), but
     * these are all current catalog keys.
     *
     * @return array<int, array{ptype:string,pvar:string,link:string}>
     */
    private function variantKits(): array
    {
        return [
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_glass',       'link' => 'frosted_pill'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_cover_hero',  'link' => 'pill_solid'],
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_classic',     'link' => 'corporate_row'],
            ['ptype' => 'profile_card_v4', 'pvar' => 'identity_minimal_dark','link' => 'square_sharp'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_magazine',    'link' => 'outline_pill'],
            ['ptype' => 'profile_card_v3', 'pvar' => 'identity_founder',     'link' => 'card_lifted'],
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_split',       'link' => 'pill_glass_dark'],
            ['ptype' => 'profile_card_v3', 'pvar' => 'identity_floating',    'link' => 'card_arch'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_gradient',    'link' => 'brutalist'],
            ['ptype' => 'profile_card_v4', 'pvar' => 'identity_gradient',    'link' => 'cta_glow'],
        ];
    }

    /**
     * Resolve a curated design variant into a full baked `_style` payload
     * (STYLE_DEFAULTS + the catalog variant's style + the current catalog
     * VERSION stamp). Baking the full style — rather than just stashing a
     * `_variant` key — means BOTH the applied block (via the model's
     * `retrieved` migrateStaleVariant hook) AND the no-DB template preview
     * (PreviewBiolinkBlock, which never fires that hook) render the variant
     * identically. Mirrors BiolinkBlockController::applyVariant() /
     * BiolinkBlock::migrateStaleVariant().
     *
     * @param  array<string,mixed>  $extra  Extra `_style` keys (e.g. grid_span).
     * @return array<string,mixed>
     */
    private function variantStyle(string $type, string $key, array $extra = []): array
    {
        $variant = BlockVariantCatalog::find($type, $key);
        $style = is_array($variant['style'] ?? null) ? $variant['style'] : [];
        $merged = array_merge(BiolinkBlock::STYLE_DEFAULTS, $style, $extra);
        if ($variant !== null) {
            $merged['_variant'] = $key;
            $merged['_variant_version'] = BlockVariantCatalog::VERSION;
        }
        return $merged;
    }

    /* ──────────────────────── theme presets ──────────────────────── */

    /**
     * Return the bank of biolink theme presets. Each preset is a settings
     * array merged into the saved snapshot's `biolink` key. Presets cover
     * animated bg-templates, gradients, photo, and solid light/dark looks
     * with matching font/button colors and varied button shapes.
     *
     * @return array<int, array<string, mixed>>
     */
    private function themePresets(): array
    {
        $bg = fn(string $slug): ?int => $this->bgTemplateMap()[$slug] ?? null;

        $presets = [];

        // 0 — Aurora animated
        if ($id = $bg('aurora-borealis')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#7c3aed',
                'font_color'        => '#ffffff',
                'button_color'      => '#7c3aed',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        }

        // 1 — Bold gradient (sunset)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(135deg, #f97316 0%, #ec4899 50%, #8b5cf6 100%)',
            'theme_color'        => '#ec4899',
            'font_color'         => '#ffffff',
            'button_color'       => '#ffffff',
            'button_text_color'  => '#1f2937',
            'button_style'       => 'pill',
        ];

        // 2 — Soft pastel paper (light)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(180deg, #fdf6e3 0%, #fce7f3 100%)',
            'theme_color'        => '#0ea5e9',
            'font_color'         => '#1f2937',
            'button_color'       => '#0ea5e9',
            'button_text_color'  => '#ffffff',
            'button_style'       => 'rounded',
        ];

        // 3 — Mono dark (sharp)
        $presets[] = [
            'background_type'   => 'color',
            'background_color'  => '#0a0a0a',
            'theme_color'       => '#f5f5f5',
            'font_color'        => '#f5f5f5',
            'button_color'      => '#f5f5f5',
            'button_text_color' => '#0a0a0a',
            'button_style'      => 'square',
        ];

        // 4 — Editorial photo
        $presets[] = [
            'background_type'   => 'image',
            'background_image'  => $this->photo('minimal,texture', 1200, 2000, 'tpl-bg-editorial'),
            'theme_color'       => '#f59e0b',
            'font_color'        => '#ffffff',
            'button_color'      => '#ffffff',
            'button_text_color' => '#0f172a',
            'button_style'      => 'outline',
        ];

        // 5 — Neon cyber animated (or fallback to neon gradient)
        if ($id = $bg('neon-waves')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#a855f7',
                'font_color'        => '#ffffff',
                'button_color'      => '#a855f7',
                'button_text_color' => '#ffffff',
                'button_style'      => 'shadow',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #0f172a 0%, #581c87 50%, #a855f7 100%)',
                'theme_color'        => '#a855f7',
                'font_color'         => '#ffffff',
                'button_color'       => '#a855f7',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'shadow',
            ];
        }

        // 6 — Ocean gradient (calm)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(160deg, #0c4a6e 0%, #0e7490 60%, #06b6d4 100%)',
            'theme_color'        => '#06b6d4',
            'font_color'         => '#f0fdff',
            'button_color'       => '#06b6d4',
            'button_text_color'  => '#001018',
            'button_style'       => 'pill',
        ];

        // 7 — Smoke fog animated (or moody gradient fallback)
        if ($id = $bg('smoke-fog')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#94a3b8',
                'font_color'        => '#f8fafc',
                'button_color'      => '#1e293b',
                'button_text_color' => '#f8fafc',
                'button_style'      => 'outline',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #1f2937 0%, #374151 100%)',
                'theme_color'        => '#94a3b8',
                'font_color'         => '#f8fafc',
                'button_color'       => '#1e293b',
                'button_text_color'  => '#f8fafc',
                'button_style'       => 'outline',
            ];
        }

        // 8 — Prism light animated (or warm light gradient)
        if ($id = $bg('prism-light')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#10b981',
                'font_color'        => '#ffffff',
                'button_color'      => '#10b981',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #fef3c7 0%, #fbbf24 100%)',
                'theme_color'        => '#10b981',
                'font_color'         => '#1f2937',
                'button_color'       => '#10b981',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'rounded',
            ];
        }

        // 9 — Deep ocean animated (or deep gradient fallback)
        if ($id = $bg('deep-ocean')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#7c3aed',
                'font_color'        => '#e0e7ff',
                'button_color'      => '#7c3aed',
                'button_text_color' => '#ffffff',
                'button_style'      => 'pill',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #020617 0%, #1e1b4b 100%)',
                'theme_color'        => '#7c3aed',
                'font_color'         => '#e0e7ff',
                'button_color'       => '#7c3aed',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'pill',
            ];
        }

        return $presets;
    }

    /** @return array<string,int> */
    private function bgTemplateMap(): array
    {
        if ($this->bgTemplateMap === null) {
            try {
                $this->bgTemplateMap = BgTemplate::query()
                    ->pluck('id', 'slug')
                    ->map(fn($id) => (int) $id)
                    ->all();
            } catch (\Throwable $e) {
                // Table may not exist yet on first boot — degrade gracefully.
                $this->bgTemplateMap = [];
            }
        }
        return $this->bgTemplateMap;
    }

    /* ──────────────────── snapshot + block helpers ──────────────────── */

    private function snapshot(array $blocks, array $biolink = []): array
    {
        // `meta.seed_version` lets a future seeder run detect rows
        // generated by an older blueprint version and auto-refresh them
        // (see `autoRefreshStaleVersions()`). Anything else admins or
        // future blocks want to stash on the snapshot is preserved.
        return [
            'biolink' => $biolink,
            'blocks'  => $blocks,
            'meta'    => ['seed_version' => self::SEED_VERSION],
        ];
    }

    /**
     * Refresh seed-generated persona rows whose stored `seed_version`
     * is older than the current SEED_VERSION. For each persona we walk
     * its current blueprint set and, for any row that:
     *
     *  - lives at a known blueprint slug (admin-added rows in the
     *    `persona-<slug>-*` namespace are skipped — unknown slug),
     *  - has `updated_at` within EDIT_DRIFT_TOLERANCE of `created_at`
     *    (admin edits through the panel are preserved — same heuristic
     *    as `RefreshPersonaSeed`), and
     *  - carries a `meta.seed_version` lower than SEED_VERSION,
     *
     * we delete the stale row and immediately recreate it from the
     * current blueprint targeting the SAME slug. Slug-targeted refresh
     * is required because the count-based fill loop in `run()` only
     * tops personas up to MIN_PER_PERSONA — if a persona already has
     * enough templates (e.g. admin-added ones), the gap-fill would
     * never recreate the deleted slug. Refreshing inline guarantees
     * every untouched, current-blueprint slug ends up at SEED_VERSION
     * regardless of how many other templates the persona carries.
     *
     * Idempotent: once every row is at the current version this method
     * is a true no-op on every subsequent run.
     */
    private function autoRefreshStaleVersions(): void
    {
        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];

            // Build a slug => [blueprint, index] map so we can recreate
            // a refreshed row with the exact same sort_order it had.
            $blueprintBySlug = [];
            foreach ($this->blueprintsFor($persona) as $i => $bp) {
                $bpSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);
                $blueprintBySlug[$bpSlug] = ['bp' => $bp, 'i' => $i];
            }
            if (empty($blueprintBySlug)) {
                continue;
            }

            $rows = PageTemplate::query()
                ->where('slug', 'like', 'persona-' . $slug . '-%')
                ->get(['id', 'slug', 'snapshot', 'created_at', 'updated_at']);

            foreach ($rows as $row) {
                if (!isset($blueprintBySlug[$row->slug])) {
                    continue; // unknown slug — admin-added, leave alone.
                }
                if ($row->updated_at && $row->created_at
                    && $row->updated_at->getTimestamp() - $row->created_at->getTimestamp() > self::EDIT_DRIFT_TOLERANCE) {
                    continue; // admin edited through the panel — preserve.
                }
                $stored = (int) (((array) $row->snapshot)['meta']['seed_version'] ?? 0);
                if ($stored >= self::SEED_VERSION) {
                    continue;
                }

                // Slug-targeted refresh: drop the stale row and rebuild
                // it from the current blueprint at the same slug. We
                // can't rely on the count-based gap-fill below because
                // personas with admin-added rows may already meet
                // MIN_PER_PERSONA and the deleted slug would never come
                // back.
                $entry = $blueprintBySlug[$row->slug];
                PageTemplate::whereKey($row->id)->delete();
                $this->createBlueprintRow($slug, $entry['bp'], $entry['i']);
            }
        }
    }

    /**
     * Insert one persona blueprint row. Shared between the count-based
     * gap-fill (in `run()`) and the per-slug auto-refresh path so both
     * stamp identical fields, including `snapshot.meta.seed_version`.
     *
     * @param  array{key:string,name:string,description:string,thumb:string,snapshot:array}  $bp
     */
    private function createBlueprintRow(string $personaSlug, array $bp, int $index): void
    {
        PageTemplate::create([
            'slug'                 => 'persona-' . $personaSlug . '-' . Str::slug($bp['key']),
            'name'                 => $bp['name'],
            'category'             => $personaSlug,
            'description'          => $bp['description'],
            'thumbnail_url'        => $bp['thumb'],
            'plan_tier'            => null,
            'is_active'            => true,
            'sort_order'           => 100 + $index,
            'recommended_personas' => [$personaSlug],
            'snapshot'             => $bp['snapshot'],
        ]);
    }

    private function block(string $type, array $settings): array
    {
        return ['type' => $type, 'settings' => $settings, 'is_active' => true];
    }

    /**
     * Rich profile card. The `$kit` selects the profile block type
     * (profile_card_v1..v4) and the `identity_*` design variant, whose
     * baked `_style` carries the `_profile_layout`. v3 (Stats) and v4
     * (Badges) get sensible placeholder stats/badges so they render full.
     *
     * @param  array{ptype:string,pvar:string,link:string}  $kit
     * @param  array<string,mixed>  $extra
     */
    private function profile(string $label, string $blurb, string $avatar, array $kit, string $cover = '', array $extra = []): array
    {
        $type = $kit['ptype'];
        $settings = array_merge([
            'name'      => 'Your Name',
            'title'     => $label,
            'avatar'    => $avatar,
            'cover'     => $cover,
            'bio'       => $blurb,
            'verified'  => true,
            'location'  => 'Your City, Country',
            'website'   => 'https://example.com',
            'cta_label' => 'Get in touch',
            'cta_url'   => 'https://example.com',
            'socials'   => $this->profileSocials(),
            '_style'    => $this->variantStyle($type, $kit['pvar']),
        ], $extra);

        if ($type === 'profile_card_v3' && !isset($settings['stats'])) {
            $settings['stats'] = [
                ['label' => 'Followers', 'value' => '12.4K'],
                ['label' => 'Projects',  'value' => '87'],
                ['label' => 'Years',     'value' => '6'],
            ];
        }
        if ($type === 'profile_card_v4' && !isset($settings['badges'])) {
            $settings['badges'] = [
                ['label' => 'Top Rated'],
                ['label' => 'Verified'],
                ['label' => 'Fast Replies'],
            ];
        }

        return $this->block($type, $settings);
    }

    /** @return array<int, array{name:string,url:string}> */
    private function profileSocials(): array
    {
        return [
            ['name' => 'instagram', 'url' => 'https://instagram.com/yourhandle'],
            ['name' => 'tiktok',    'url' => 'https://tiktok.com/@yourhandle'],
            ['name' => 'youtube',   'url' => 'https://youtube.com/@yourhandle'],
            ['name' => 'linkedin',  'url' => 'https://linkedin.com/in/yourhandle'],
        ];
    }

    private function heading(string $text, string $size = 'h3'): array
    {
        return $this->block('heading', ['text' => $text, 'size' => $size, 'align' => 'center']);
    }

    private function paragraph(string $text): array
    {
        return $this->block('paragraph', ['text' => $text, 'align' => 'center']);
    }

    /** @param  array{ptype:string,pvar:string,link:string}|null  $kit */
    private function link(string $text, string $url, string $icon = '', ?array $kit = null): array
    {
        $settings = ['text' => $text, 'url' => $url, 'icon' => $icon];
        if ($kit !== null) {
            $settings['_style'] = $this->variantStyle('link', $kit['link']);
        }
        return $this->block('link', $settings);
    }

    /** @param  array{ptype:string,pvar:string,link:string}|null  $kit */
    private function linkBig(string $text, string $url, string $icon = '', ?array $kit = null): array
    {
        $settings = ['text' => $text, 'url' => $url, 'icon' => $icon];
        if ($kit !== null) {
            $settings['_style'] = $this->variantStyle('link_big', $kit['link']);
        }
        return $this->block('link_big', $settings);
    }

    /** @param  array<int, array{question:string,answer:string}>  $items */
    private function faq(array $items): array
    {
        return $this->block('faq', ['items' => array_values($items)]);
    }

    /** @param  array<int, array{question:string,options:array<int,string>,correct:int}>  $questions */
    private function quiz(string $title, array $questions): array
    {
        return $this->block('quiz', ['title' => $title, 'questions' => array_values($questions)]);
    }

    /** @param  array<int, array{title:string,description:string,date:string}>  $items */
    private function timeline(array $items): array
    {
        return $this->block('timeline', ['items' => array_values($items)]);
    }

    private function product(string $name, string $description, string $price, string $image, string $url, string $badge = ''): array
    {
        return $this->block('product', [
            'name'            => $name,
            'description'     => $description,
            'price'          => $price,
            'image'          => $image,
            'url'            => $url,
            'badge'          => $badge,
            'native_checkout' => false,
        ]);
    }

    private function socials(): array
    {
        // Seed a deterministic set of placeholder platforms so the icon
        // row actually renders in preview. The user replaces these with
        // their own handles after picking the template.
        return $this->block('socials_multi', [
            'groups' => [[
                'label'     => 'Personal',
                'platforms' => [
                    ['name' => 'instagram', 'url' => 'https://instagram.com/yourhandle', 'display' => 'icon'],
                    ['name' => 'tiktok',    'url' => 'https://tiktok.com/@yourhandle',  'display' => 'icon'],
                    ['name' => 'youtube',   'url' => 'https://youtube.com/@yourhandle', 'display' => 'icon'],
                    ['name' => 'twitter',   'url' => 'https://x.com/yourhandle',        'display' => 'icon'],
                    ['name' => 'linkedin',  'url' => 'https://linkedin.com/in/yourhandle', 'display' => 'icon'],
                ],
            ]],
            'size'  => 'md',
            'style' => 'rounded',
        ]);
    }

    private function emailCollector(): array
    {
        return $this->block('email_collector', ['placeholder' => 'you@email.com', 'button_text' => 'Subscribe']);
    }

    private function image(string $url = ''): array
    {
        return $this->block('image', ['url' => $url, 'alt' => '']);
    }

    private function imageGrid(array $images = [], int $columns = 3): array
    {
        return $this->block('image_grid', [
            'columns' => $columns,
            'gap'     => 2,
            'images'  => array_map(fn($u) => ['url' => $u], $images),
        ]);
    }

    private function divider(): array
    {
        return $this->block('divider', []);
    }

    private function list(array $items): array
    {
        return $this->block('list', ['items' => $items]);
    }

    /* ─── new richer blocks ─── */

    private function countdown(string $title, string $relative = '+30 days'): array
    {
        $target = now()->modify($relative)->toIso8601String();
        return $this->block('countdown', ['title' => $title, 'target_date' => $target]);
    }

    private function video(string $url): array
    {
        return $this->block('video', ['url' => $url, 'autoplay' => false]);
    }

    private function testimonials(array $items): array
    {
        return $this->block('testimonials', ['items' => $items]);
    }

    private function review(string $name, int $rating, string $text, string $avatar = ''): array
    {
        return $this->block('review', [
            'name'   => $name,
            'avatar' => $avatar,
            'rating' => $rating,
            'text'   => $text,
        ]);
    }

    private function service(string $name, string $icon, string $price, string $description, string $url): array
    {
        return $this->block('service', [
            'name'        => $name,
            'icon'        => 'fas ' . $icon,
            'price'       => $price,
            'description' => $description,
            'url'         => $url,
        ]);
    }

    private function price(string $title, string $amount, string $period, array $features, string $url): array
    {
        return $this->block('price', [
            'title'    => $title,
            'amount'   => $amount,
            'period'   => $period,
            'features' => $features,
            'url'      => $url,
        ]);
    }

    private function ctaButton(string $text, string $url, string $color = '#7c3aed', string $textColor = '#ffffff', string $size = 'lg'): array
    {
        return $this->block('cta_button', [
            'text'       => $text,
            'url'        => $url,
            'color'      => $color,
            'text_color' => $textColor,
            'size'       => $size,
        ]);
    }

    private function contactForm(string $title, string $buttonText): array
    {
        return $this->block('contact_form', [
            'title'           => $title,
            'button_text'     => $buttonText,
            'success_message' => 'Got it — I\'ll get back to you soon.',
        ]);
    }

    private function poll(string $question, array $options): array
    {
        return $this->block('poll', ['question' => $question, 'options' => array_values($options)]);
    }

    private function qrCode(string $url, int $size = 200): array
    {
        return $this->block('qr_code', ['url' => $url, 'size' => $size]);
    }

    private function donation(string $title, string $description, array $amounts, string $url): array
    {
        return $this->block('donation', [
            'title'       => $title,
            'description' => $description,
            'amounts'     => array_values($amounts),
            'url'         => $url,
        ]);
    }

    private function coupon(string $code, string $description, string $expires): array
    {
        return $this->block('coupon', ['code' => $code, 'description' => $description, 'expires' => $expires]);
    }

    private function vcard(string $name, string $title, string $company, string $phone, string $email, string $website): array
    {
        return $this->block('vcard', [
            'name'    => $name,
            'title'   => $title,
            'company' => $company,
            'phone'   => $phone,
            'email'   => $email,
            'website' => $website,
        ]);
    }

    /**
     * Card container with children — renders a small grid of child blocks
     * inside one styled card. Keeps the variant from devolving back into
     * a plain link list.
     */
    private function cardGrid(string $title, int $columns, array $children): array
    {
        $card = $this->block('card', [
            'title'         => $title,
            'columns'       => $columns,
            'gap'           => 12,
            'padding'       => 16,
            'border_radius' => 16,
            'bg_type'       => 'glass',
            'glass_opacity' => 6,
            'glass_blur'    => 12,
            'shadow'        => 'sm',
        ]);
        $card['children'] = array_values($children);
        return $card;
    }

    /* ──────────────────── realistic demo imagery ──────────────────── */

    /**
     * Persona slug => a LoremFlickr-friendly photo keyword so each
     * persona's templates pull on-topic imagery instead of random
     * placeholders. Visually-concrete slugs (chef, yoga, restaurant…)
     * fall through to the slug itself; only abstract/ambiguous ones are
     * remapped here.
     *
     * @var array<string,string>
     */
    private const PERSONA_IMAGE_KEYWORDS = [
        'creator'    => 'creative,workspace',
        'influencer' => 'lifestyle,social',
        'coach'      => 'coaching,office',
        'business'   => 'business,office',
        'developer'  => 'developer,code',
        'consultant' => 'business,meeting',
        'freelancer' => 'laptop,workspace',
        'agency'     => 'office,team',
        'realestate' => 'realestate,house',
        'nonprofit'  => 'volunteer,community',
        'community'  => 'community,people',
        'student'    => 'study,campus',
        'author'     => 'books,writing',
        'journalist' => 'newsroom,writing',
        'trainer'    => 'gym,training',
        'model'      => 'fashion,model',
        'beauty'     => 'beauty,makeup',
        'event'      => 'event,celebration',
        'other'      => 'minimal,abstract',
    ];

    /** Map a persona slug to a photo keyword (fallback = the slug itself). */
    private function personaKeyword(string $slug): string
    {
        return self::PERSONA_IMAGE_KEYWORDS[$slug] ?? $slug;
    }

    /**
     * Deterministic, keyword-matched real photo from LoremFlickr (a
     * placeholder CDN like the old picsum, but topical). The `$seed`
     * locks a stable image per slot so re-seeding is idempotent.
     */
    private function photo(string $keywords, int $w, int $h, string $seed): string
    {
        $lock = (crc32($seed) % 100000) + 1;
        return "https://loremflickr.com/{$w}/{$h}/" . rawurlencode($keywords) . "?lock={$lock}";
    }

    /** Deterministic realistic-face photo (pravatar) keyed by `$seed`. */
    private function face(string $seed, int $size = 200): string
    {
        $n = (crc32($seed) % 70) + 1; // pravatar serves img=1..70
        return "https://i.pravatar.cc/{$size}?img={$n}";
    }

    /* ──────────────────── newer block helpers ──────────────────── */

    /** @param  array<int, array{question:string,answer:string,icon?:string}>  $items */
    private function faqV2(array $items): array
    {
        return $this->block('faq_v2', ['items' => array_values($items)]);
    }

    private function badge(string $text, string $color = '#7c3aed', string $textColor = '#ffffff'): array
    {
        return $this->block('badge', ['text' => $text, 'color' => $color, 'text_color' => $textColor]);
    }

    private function alert(string $text, string $type = 'info', string $icon = 'fa-info-circle'): array
    {
        return $this->block('alert', ['text' => $text, 'type' => $type, 'icon' => $icon]);
    }

    /** @param  array<int, array{label:string,value:int,color?:string}>  $items */
    private function progress(array $items): array
    {
        return $this->block('progress', ['items' => array_values($items)]);
    }

    /** @param  array<int, array{name:string,price:string,included?:bool}>  $items */
    private function listPricing(array $items): array
    {
        return $this->block('list_pricing', ['items' => array_values($items)]);
    }

    private function oneTimeOffer(string $title, string $description, string $price, string $originalPrice, string $url): array
    {
        return $this->block('one_time_offer', [
            'title'          => $title,
            'description'    => $description,
            'price'          => $price,
            'original_price' => $originalPrice,
            'url'            => $url,
        ]);
    }

    /** @param  array<int,string>  $images */
    private function imageSlider(array $images, int $interval = 3500): array
    {
        return $this->block('image_slider', [
            'images'   => array_map(fn($u) => ['url' => $u], array_values($images)),
            'interval' => $interval,
            'effect'   => 'fade',
        ]);
    }

    private function whatsapp(string $phone, string $buttonText = 'Chat on WhatsApp', string $message = ''): array
    {
        return $this->block('whatsapp_widget', [
            'phone'       => $phone,
            'button_text' => $buttonText,
            'message'     => $message,
        ]);
    }
}
