<?php

namespace Database\Seeders;

use App\Modules\Admin\Models\BgTemplate;
use App\Modules\Admin\Models\PageTemplate;
use App\Modules\User\Models\BiolinkBlock;
use App\Modules\User\Services\PersonaCatalog;
use App\Modules\User\Support\BlockVariantCatalog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * Ensures every persona has at least 10 active page templates so the
 * onboarding "Recommended for you" shelf is populated for everyone.
 *
 * Idempotent: a persona that already has >= 10 active templates tagged
 * with that slug in `recommended_personas` is skipped entirely so admin
 * curation isn't clobbered. Templates are also keyed by a stable slug
 * (`persona-<slug>-<variant>`) so re-running this seeder never overwrites
 * an existing row.
 *
 * Each variant rotates through a bank of theme presets so a persona's
 * shelf shows a real spread of looks (animated backgrounds, gradients,
 * photo, light/dark solids) and block mixes (countdown, image_grid,
 * video, testimonials, service, price, cta_button, contact_form, poll,
 * qr_code, card, review, donation, coupon, etc.) — not ten variations
 * of the same beige starter page.
 */
class ExpandedPageTemplateLibrarySeeder extends Seeder
{
    private const MIN_PER_PERSONA = 10;

    /**
     * Blueprint version stamped into every seeded row's
     * `snapshot.meta.seed_version`. Bump this whenever the blueprints in
     * `blueprintsFor()` or `themePresets()` change so the next deploy
     * auto-refreshes untouched persona rows that were generated by an
     * older blueprint version. Admin-edited rows are still preserved
     * (same `updated_at` heuristic as `RefreshPersonaSeed`).
     *
     * IMPORTANT: keep blueprint `key` values stable across redesigns.
     * The auto-refresh in `autoRefreshStaleVersions()` matches stale
     * rows by their `persona-<slug>-<key>` slug — if a redesign renames
     * a blueprint `key`, old rows at the previous slug fall into the
     * "unknown slug — admin-added" bucket and are deliberately left
     * alone. Redesign block contents/copy/themes freely; rename the
     * `key` only when you also intend to retire the old slug.
     */
    public const SEED_VERSION = 6;

    /**
     * Personas whose "Aurora Starter" blueprint ships as a design-locked
     * designer template (~12 total). Applying one of these stamps the
     * biolink design-locked: content stays editable but styling follows
     * the template until the user detaches. Admins can flip the lock per
     * template in the admin panel afterwards.
     *
     * @var array<int,string>
     */
    private const DESIGN_LOCKED_STARTER_PERSONAS = [
        'creator', 'artist', 'musician', 'influencer', 'coach', 'business',
        'developer', 'photographer', 'podcaster', 'fitness', 'restaurant',
        'realestate',
    ];

    /** Tolerance (seconds) for treating updated_at == created_at. */
    private const EDIT_DRIFT_TOLERANCE = 2;

    /** @var array<string,int|null>|null Cached slug => bg_template id map. */
    private ?array $bgTemplateMap = null;

    public function run(): void
    {
        // Auto-refresh: drop untouched seeded rows whose stored
        // seed_version is older than the current SEED_VERSION so the
        // next deploy after a blueprint redesign rolls forward without
        // anyone having to invoke `templates:refresh-persona-seed`.
        // The fill loop below recreates them with the new design.
        $this->autoRefreshStaleVersions();

        $countsBySlug = [];
        PageTemplate::query()->where('is_active', true)->get(['recommended_personas'])->each(function ($t) use (&$countsBySlug) {
            foreach ((array) ($t->recommended_personas ?? []) as $slug) {
                $countsBySlug[$slug] = ($countsBySlug[$slug] ?? 0) + 1;
            }
        });

        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];
            $have = $countsBySlug[$slug] ?? 0;
            if ($have >= self::MIN_PER_PERSONA) {
                continue;
            }

            $blueprints = $this->blueprintsFor($persona);
            $needed = self::MIN_PER_PERSONA - $have;
            $created = 0;

            foreach ($blueprints as $i => $bp) {
                if ($created >= $needed) break;
                $tplSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);

                if (PageTemplate::where('slug', $tplSlug)->exists()) {
                    continue;
                }

                $this->createBlueprintRow($slug, $bp, $i);
                $created++;
            }
        }
    }

    /**
     * Build the 10 blueprint variants for a persona. Variant `key`s are
     * stable so the resulting slug `persona-<slug>-<key>` stays identical
     * across re-runs (idempotent).
     *
     * @return array<int, array{key:string,name:string,description:string,thumb:string,snapshot:array}>
     */
    public function blueprintsFor(array $persona): array
    {
        $slug   = $persona['slug'];
        $label  = $persona['label'] ?? ucfirst($slug);
        $blurb  = $persona['blurb'] ?? 'Everything you do, in one place.';
        $kw     = $this->personaKeyword($slug);
        $kits   = $this->variantKits();
        $themes = $this->themePresets();
        // Rotate the theme bank so different personas lead with different
        // looks (persona shelf #0 isn't always the same aurora page).
        $offset = crc32($slug) % max(count($themes), 1);
        $theme  = fn(int $i): array => $themes[($i + $offset) % count($themes)];

        $face  = $this->face('tpl-' . $slug . '-face');
        $cover = $this->photo($kw, 1200, 480, 'tpl-' . $slug . '-cover');
        $sq    = fn(string $seed): string => $this->photo($kw, 600, 600, 'tpl-' . $slug . '-' . $seed);
        $tall  = fn(string $seed): string => $this->photo($kw, 900, 1200, 'tpl-' . $slug . '-' . $seed);
        $thumb = fn(string $key): string => $this->photo($kw, 640, 800, 'tpl-thumb-' . $slug . '-' . $key);

        return [
            // 0 — Starter: the flagship page (design-locked for key personas).
            [
                'key'         => 'starter',
                'name'        => $label . ' Starter',
                'description' => 'A polished all-rounder for ' . strtolower($label) . ' pages — profile, socials, top links and a mailing-list capture.',
                'thumb'       => $thumb('starter'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[0], $cover),
                    $this->socials(),
                    $this->link('My latest work', 'https://example.com/latest', 'fas fa-star', $kits[0]),
                    $this->link('Work with me', 'https://example.com/work-with-me', 'fas fa-handshake', $kits[0]),
                    $this->link('All my links', 'https://example.com/links', 'fas fa-link', $kits[0]),
                    $this->divider(),
                    $this->heading('Stay in the loop'),
                    $this->emailCollector(),
                ], $theme(0)),
            ],

            // 1 — Spotlight: bold hero, big links, a highlight reel + praise.
            [
                'key'         => 'spotlight',
                'name'        => $label . ' Spotlight',
                'description' => 'A bold, image-led page with big tappable links, a highlight slider and social proof.',
                'thumb'       => $thumb('spotlight'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[1], $cover),
                    $this->badge('FEATURED'),
                    $this->linkBig('See the latest', 'https://example.com/latest', 'fas fa-fire', $kits[1]),
                    $this->linkBig('Behind the scenes', 'https://example.com/bts', 'fas fa-camera', $kits[1]),
                    $this->imageSlider([$tall('sp1'), $tall('sp2'), $tall('sp3')]),
                    $this->testimonials([
                        ['name' => 'Alex M.',  'text' => 'Exactly what I was looking for — professional and fast.'],
                        ['name' => 'Riley T.', 'text' => 'One of the best around. Highly recommended.'],
                    ]),
                    $this->socials(),
                ], $theme(1)),
            ],

            // 2 — Storefront: products, an offer and a coupon.
            [
                'key'         => 'storefront',
                'name'        => $label . ' Storefront',
                'description' => 'Sell from your page: featured products, a limited-time offer and a coupon code.',
                'thumb'       => $thumb('storefront'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[2]),
                    $this->alert('Free shipping on orders over $50 this week.', 'info', 'fa-truck-fast'),
                    $this->product('Signature item', 'The one everyone asks about.', '$39', $sq('p1'), 'https://example.com/shop/1', 'Best seller'),
                    $this->product('New arrival', 'Fresh this season — limited run.', '$54', $sq('p2'), 'https://example.com/shop/2', 'New'),
                    $this->oneTimeOffer('Bundle deal', 'Get both together and save.', '$79', '$93', 'https://example.com/shop/bundle'),
                    $this->coupon('WELCOME10', '10% off your first order', '+30 days'),
                    $this->ctaButton('Browse the full shop', 'https://example.com/shop'),
                ], $theme(2)),
            ],

            // 3 — Booking: services, a price card and a contact form.
            [
                'key'         => 'booking',
                'name'        => $label . ' Bookings',
                'description' => 'Turn visits into clients: services with prices, a package card and an inquiry form.',
                'thumb'       => $thumb('booking'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[3]),
                    $this->heading('Services'),
                    $this->service('Intro session', 'fa-comments', '$49', 'A quick first session to see if we\'re a fit.', 'https://example.com/book/intro'),
                    $this->service('Full package', 'fa-gem', '$249', 'The complete experience, start to finish.', 'https://example.com/book/full'),
                    $this->price('Monthly retainer', '$99', 'per month', ['Priority scheduling', 'Unlimited messages', 'Cancel anytime'], 'https://example.com/book/retainer'),
                    $this->contactForm('Tell me what you need', 'Send inquiry'),
                ], $theme(3)),
            ],

            // 4 — Gallery: editorial photo look, work grid and video.
            [
                'key'         => 'gallery',
                'name'        => $label . ' Gallery',
                'description' => 'A visual-first page: a photo grid, featured video and a portfolio link.',
                'thumb'       => $thumb('gallery'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[4], $cover),
                    $this->heading('Recent work'),
                    $this->imageGrid([$sq('g1'), $sq('g2'), $sq('g3'), $sq('g4'), $sq('g5'), $sq('g6')], 3),
                    $this->video('https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
                    $this->linkBig('View the full portfolio', 'https://example.com/portfolio', 'fas fa-images', $kits[4]),
                    $this->socials(),
                ], $theme(4)),
            ],

            // 5 — Launch: countdown, progress and early-access capture.
            [
                'key'         => 'launch',
                'name'        => $label . ' Launch',
                'description' => 'Build hype for what\'s next: countdown, launch progress, early-access signup and FAQ.',
                'thumb'       => $thumb('launch'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[5]),
                    $this->countdown('Something big drops in', '+14 days'),
                    $this->progress([
                        ['label' => 'Production', 'value' => 90],
                        ['label' => 'Early access spots claimed', 'value' => 65],
                    ]),
                    $this->heading('Get early access'),
                    $this->emailCollector(),
                    $this->faqV2([
                        ['question' => 'When does it launch?', 'answer' => 'Two weeks from now — subscribers hear first.'],
                        ['question' => 'Will there be a discount?', 'answer' => 'Early-access members get launch-week pricing.'],
                    ]),
                ], $theme(5)),
            ],

            // 6 — Community: poll, milestones timeline and support options.
            [
                'key'         => 'community',
                'name'        => $label . ' Community',
                'description' => 'Bring people together: a live poll, your story so far and ways to support the work.',
                'thumb'       => $thumb('community'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[6]),
                    $this->poll('What should we do next?', ['More events', 'More content', 'A members-only space']),
                    $this->heading('The story so far'),
                    $this->timeline([
                        ['title' => 'The beginning',  'description' => 'Started with an idea and a handful of supporters.', 'date' => '2023'],
                        ['title' => 'Growing fast',    'description' => 'Hit our first big milestone together.',             'date' => '2024'],
                        ['title' => 'Where we\'re going', 'description' => 'Bigger plans — and you\'re part of them.',       'date' => 'Now'],
                    ]),
                    $this->donation('Support the work', 'Every bit helps keep this going.', [5, 15, 50], 'https://example.com/support'),
                    $this->link('Join the community', 'https://example.com/join', 'fas fa-people-group', $kits[6]),
                ], $theme(6)),
            ],

            // 7 — Contact card: vCard, quick facts, QR and WhatsApp.
            [
                'key'         => 'contact-card',
                'name'        => $label . ' Contact Card',
                'description' => 'A digital business card: save-my-contact, quick facts, a scannable QR and one-tap chat.',
                'thumb'       => $thumb('contact-card'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[7]),
                    $this->vcard('Your Name', $label, 'Your Company', '+1 555 123 4567', 'you@example.com', 'https://example.com'),
                    $this->list([
                        'Based in Your City — available worldwide',
                        'Replies within one business day',
                        'Languages: English, Spanish',
                    ]),
                    $this->qrCode('https://example.com'),
                    $this->whatsapp('+15551234567', 'Message me on WhatsApp'),
                ], $theme(7)),
            ],

            // 8 — Reviews & offers: social proof heavy with a deal attached.
            [
                'key'         => 'reviews',
                'name'        => $label . ' Reviews & Offers',
                'description' => 'Lead with proof: star reviews and client praise, plus a coupon and pricing list.',
                'thumb'       => $thumb('reviews'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[8]),
                    $this->review('Jordan P.', 5, 'Absolutely fantastic — exceeded every expectation.', $this->face('tpl-' . $slug . '-r1')),
                    $this->review('Casey L.', 5, 'Professional, friendly and worth every penny.', $this->face('tpl-' . $slug . '-r2')),
                    $this->listPricing([
                        ['name' => 'Standard',  'price' => '$29'],
                        ['name' => 'Popular',   'price' => '$59'],
                        ['name' => 'Premium',   'price' => '$99'],
                    ]),
                    $this->coupon('FIVESTAR', '15% off — reviews readers only', '+21 days'),
                    $this->ctaButton('Book now', 'https://example.com/book'),
                ], $theme(8)),
            ],

            // 9 — Minimal: quiet, focused link list with a single alert.
            [
                'key'         => 'minimal',
                'name'        => $label . ' Minimal',
                'description' => 'A quiet, distraction-free page: your profile and a clean set of links. Nothing else.',
                'thumb'       => $thumb('minimal'),
                'snapshot'    => $this->snapshot([
                    $this->profile($label, $blurb, $face, $kits[9]),
                    $this->alert('New here? Start with the first link below.', 'info', 'fa-circle-info'),
                    $this->link('Start here', 'https://example.com/start', 'fas fa-arrow-right', $kits[9]),
                    $this->link('About me', 'https://example.com/about', 'fas fa-user', $kits[9]),
                    $this->link('My work', 'https://example.com/work', 'fas fa-briefcase', $kits[9]),
                    $this->link('Get in touch', 'mailto:you@example.com', 'fas fa-envelope', $kits[9]),
                    $this->divider(),
                    $this->socials(),
                ], $theme(9)),
            ],
        ];
    }

    /**
     * Per-blueprint "variant kit": the profile block type + identity
     * variant (which carries the `_profile_layout`) plus the link/big-link
     * design variant key used across that template. Indexed in lockstep
     * with the 10 blueprints so each template gets a distinct profile
     * layout AND a distinct link look (on top of its distinct theme
     * preset). Keys reference BlockVariantCatalog::forType() — `find()`
     * tolerates an unknown key (renderer falls back to defaults), but
     * these are all current catalog keys.
     *
     * @return array<int, array{ptype:string,pvar:string,link:string}>
     */
    private function variantKits(): array
    {
        return [
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_glass',       'link' => 'frosted_pill'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_cover_hero',  'link' => 'pill_solid'],
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_classic',     'link' => 'corporate_row'],
            ['ptype' => 'profile_card_v4', 'pvar' => 'identity_minimal_dark','link' => 'square_sharp'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_magazine',    'link' => 'outline_pill'],
            ['ptype' => 'profile_card_v3', 'pvar' => 'identity_founder',     'link' => 'card_lifted'],
            ['ptype' => 'profile_card_v1', 'pvar' => 'identity_split',       'link' => 'pill_glass_dark'],
            ['ptype' => 'profile_card_v3', 'pvar' => 'identity_floating',    'link' => 'card_arch'],
            ['ptype' => 'profile_card_v2', 'pvar' => 'identity_gradient',    'link' => 'brutalist'],
            ['ptype' => 'profile_card_v4', 'pvar' => 'identity_gradient',    'link' => 'cta_glow'],
        ];
    }

    /**
     * Resolve a curated design variant into a full baked `_style` payload
     * (STYLE_DEFAULTS + the catalog variant's style + the current catalog
     * VERSION stamp). Baking the full style — rather than just stashing a
     * `_variant` key — means BOTH the applied block (via the model's
     * `retrieved` migrateStaleVariant hook) AND the no-DB template preview
     * (PreviewBiolinkBlock, which never fires that hook) render the variant
     * identically. Mirrors BiolinkBlockController::applyVariant() /
     * BiolinkBlock::migrateStaleVariant().
     *
     * @param  array<string,mixed>  $extra  Extra `_style` keys (e.g. grid_span).
     * @return array<string,mixed>
     */
    private function variantStyle(string $type, string $key, array $extra = []): array
    {
        $variant = BlockVariantCatalog::find($type, $key);
        $style = is_array($variant['style'] ?? null) ? $variant['style'] : [];
        $merged = array_merge(BiolinkBlock::STYLE_DEFAULTS, $style, $extra);
        if ($variant !== null) {
            $merged['_variant'] = $key;
            $merged['_variant_version'] = BlockVariantCatalog::VERSION;
        }
        return $merged;
    }

    /* ──────────────────────── theme presets ──────────────────────── */

    /**
     * Return the bank of biolink theme presets. Each preset is a settings
     * array merged into the saved snapshot's `biolink` key. Presets cover
     * animated bg-templates, gradients, photo, and solid light/dark looks
     * with matching font/button colors and varied button shapes.
     *
     * @return array<int, array<string, mixed>>
     */
    private function themePresets(): array
    {
        $bg = fn(string $slug): ?int => $this->bgTemplateMap()[$slug] ?? null;

        $presets = [];

        // 0 — Aurora animated
        if ($id = $bg('aurora-borealis')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#3d6bff',
                'font_color'        => '#ffffff',
                'button_color'      => '#3d6bff',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        }

        // 1 — Bold gradient (sunset)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(135deg, #f97316 0%, #ec4899 50%, #8b5cf6 100%)',
            'theme_color'        => '#ec4899',
            'font_color'         => '#ffffff',
            'button_color'       => '#ffffff',
            'button_text_color'  => '#1f2937',
            'button_style'       => 'pill',
        ];

        // 2 — Soft pastel paper (light)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(180deg, #fdf6e3 0%, #fce7f3 100%)',
            'theme_color'        => '#0ea5e9',
            'font_color'         => '#1f2937',
            'button_color'       => '#0ea5e9',
            'button_text_color'  => '#ffffff',
            'button_style'       => 'rounded',
        ];

        // 3 — Mono dark (sharp)
        $presets[] = [
            'background_type'   => 'color',
            'background_color'  => '#0a0a0a',
            'theme_color'       => '#f5f5f5',
            'font_color'        => '#f5f5f5',
            'button_color'      => '#f5f5f5',
            'button_text_color' => '#0a0a0a',
            'button_style'      => 'square',
        ];

        // 4 — Editorial photo
        $presets[] = [
            'background_type'   => 'image',
            'background_image'  => $this->photo('minimal,texture', 1200, 2000, 'tpl-bg-editorial'),
            'theme_color'       => '#f59e0b',
            'font_color'        => '#ffffff',
            'button_color'      => '#ffffff',
            'button_text_color' => '#0f172a',
            'button_style'      => 'outline',
        ];

        // 5 — Neon cyber animated (or fallback to neon gradient)
        if ($id = $bg('neon-waves')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#a855f7',
                'font_color'        => '#ffffff',
                'button_color'      => '#a855f7',
                'button_text_color' => '#ffffff',
                'button_style'      => 'shadow',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #0f172a 0%, #581c87 50%, #a855f7 100%)',
                'theme_color'        => '#a855f7',
                'font_color'         => '#ffffff',
                'button_color'       => '#a855f7',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'shadow',
            ];
        }

        // 6 — Ocean gradient (calm)
        $presets[] = [
            'background_type'    => 'gradient',
            'background_gradient' => 'linear-gradient(160deg, #0c4a6e 0%, #0e7490 60%, #06b6d4 100%)',
            'theme_color'        => '#06b6d4',
            'font_color'         => '#f0fdff',
            'button_color'       => '#06b6d4',
            'button_text_color'  => '#001018',
            'button_style'       => 'pill',
        ];

        // 7 — Smoke fog animated (or moody gradient fallback)
        if ($id = $bg('smoke-fog')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#94a3b8',
                'font_color'        => '#f8fafc',
                'button_color'      => '#1e293b',
                'button_text_color' => '#f8fafc',
                'button_style'      => 'outline',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #1f2937 0%, #374151 100%)',
                'theme_color'        => '#94a3b8',
                'font_color'         => '#f8fafc',
                'button_color'       => '#1e293b',
                'button_text_color'  => '#f8fafc',
                'button_style'       => 'outline',
            ];
        }

        // 8 — Prism light animated (or warm light gradient)
        if ($id = $bg('prism-light')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#10b981',
                'font_color'        => '#ffffff',
                'button_color'      => '#10b981',
                'button_text_color' => '#ffffff',
                'button_style'      => 'rounded',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(135deg, #fef3c7 0%, #fbbf24 100%)',
                'theme_color'        => '#10b981',
                'font_color'         => '#1f2937',
                'button_color'       => '#10b981',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'rounded',
            ];
        }

        // 9 — Deep ocean animated (or deep gradient fallback)
        if ($id = $bg('deep-ocean')) {
            $presets[] = [
                'background_type'   => 'template',
                'bg_template_id'    => $id,
                'theme_color'       => '#3d6bff',
                'font_color'        => '#e0e7ff',
                'button_color'      => '#3d6bff',
                'button_text_color' => '#ffffff',
                'button_style'      => 'pill',
            ];
        } else {
            $presets[] = [
                'background_type'    => 'gradient',
                'background_gradient' => 'linear-gradient(180deg, #020617 0%, #1e1b4b 100%)',
                'theme_color'        => '#3d6bff',
                'font_color'         => '#e0e7ff',
                'button_color'       => '#3d6bff',
                'button_text_color'  => '#ffffff',
                'button_style'       => 'pill',
            ];
        }

        return $presets;
    }

    /** @return array<string,int> */
    private function bgTemplateMap(): array
    {
        if ($this->bgTemplateMap === null) {
            try {
                $this->bgTemplateMap = BgTemplate::query()
                    ->pluck('id', 'slug')
                    ->map(fn($id) => (int) $id)
                    ->all();
            } catch (\Throwable $e) {
                // Table may not exist yet on first boot — degrade gracefully.
                $this->bgTemplateMap = [];
            }
        }
        return $this->bgTemplateMap;
    }

    /* ──────────────────── snapshot + block helpers ──────────────────── */

    private function snapshot(array $blocks, array $biolink = []): array
    {
        // `meta.seed_version` lets a future seeder run detect rows
        // generated by an older blueprint version and auto-refresh them
        // (see `autoRefreshStaleVersions()`). Anything else admins or
        // future blocks want to stash on the snapshot is preserved.
        return [
            'biolink' => $biolink,
            'blocks'  => $blocks,
            'meta'    => ['seed_version' => self::SEED_VERSION],
        ];
    }

    /**
     * Refresh seed-generated persona rows whose stored `seed_version`
     * is older than the current SEED_VERSION. For each persona we walk
     * its current blueprint set and, for any row that:
     *
     *  - lives at a known blueprint slug (admin-added rows in the
     *    `persona-<slug>-*` namespace are skipped — unknown slug),
     *  - has `updated_at` within EDIT_DRIFT_TOLERANCE of `created_at`
     *    (admin edits through the panel are preserved — same heuristic
     *    as `RefreshPersonaSeed`), and
     *  - carries a `meta.seed_version` lower than SEED_VERSION,
     *
     * we delete the stale row and immediately recreate it from the
     * current blueprint targeting the SAME slug. Slug-targeted refresh
     * is required because the count-based fill loop in `run()` only
     * tops personas up to MIN_PER_PERSONA — if a persona already has
     * enough templates (e.g. admin-added ones), the gap-fill would
     * never recreate the deleted slug. Refreshing inline guarantees
     * every untouched, current-blueprint slug ends up at SEED_VERSION
     * regardless of how many other templates the persona carries.
     *
     * Idempotent: once every row is at the current version this method
     * is a true no-op on every subsequent run.
     */
    private function autoRefreshStaleVersions(): void
    {
        foreach (PersonaCatalog::all() as $persona) {
            $slug = $persona['slug'];

            // Build a slug => [blueprint, index] map so we can recreate
            // a refreshed row with the exact same sort_order it had.
            $blueprintBySlug = [];
            foreach ($this->blueprintsFor($persona) as $i => $bp) {
                $bpSlug = 'persona-' . $slug . '-' . Str::slug($bp['key']);
                $blueprintBySlug[$bpSlug] = ['bp' => $bp, 'i' => $i];
            }
            if (empty($blueprintBySlug)) {
                continue;
            }

            $rows = PageTemplate::query()
                ->where('slug', 'like', 'persona-' . $slug . '-%')
                ->get(['id', 'slug', 'snapshot', 'created_at', 'updated_at']);

            foreach ($rows as $row) {
                if (!isset($blueprintBySlug[$row->slug])) {
                    continue; // unknown slug — admin-added, leave alone.
                }
                if ($row->updated_at && $row->created_at
                    && $row->updated_at->getTimestamp() - $row->created_at->getTimestamp() > self::EDIT_DRIFT_TOLERANCE) {
                    continue; // admin edited through the panel — preserve.
                }
                $stored = (int) (((array) $row->snapshot)['meta']['seed_version'] ?? 0);
                if ($stored >= self::SEED_VERSION) {
                    continue;
                }

                // Slug-targeted refresh: drop the stale row and rebuild
                // it from the current blueprint at the same slug. We
                // can't rely on the count-based gap-fill below because
                // personas with admin-added rows may already meet
                // MIN_PER_PERSONA and the deleted slug would never come
                // back.
                $entry = $blueprintBySlug[$row->slug];
                PageTemplate::whereKey($row->id)->delete();
                $this->createBlueprintRow($slug, $entry['bp'], $entry['i']);
            }
        }
    }

    /**
     * Insert one persona blueprint row. Shared between the count-based
     * gap-fill (in `run()`) and the per-slug auto-refresh path so both
     * stamp identical fields, including `snapshot.meta.seed_version`.
     *
     * @param  array{key:string,name:string,description:string,thumb:string,snapshot:array}  $bp
     */
    private function createBlueprintRow(string $personaSlug, array $bp, int $index): void
    {
        PageTemplate::create([
            'slug'                 => 'persona-' . $personaSlug . '-' . Str::slug($bp['key']),
            'name'                 => $bp['name'],
            'category'             => $personaSlug,
            'description'          => $bp['description'],
            'thumbnail_url'        => $bp['thumb'],
            'plan_tier'            => null,
            'is_active'            => true,
            'sort_order'           => 100 + $index,
            'recommended_personas' => [$personaSlug],
            'snapshot'             => $bp['snapshot'],
            // Curated designer templates are seeded design-locked so the
            // pages they create keep the designed look (detachable).
            'design_locked'        => $bp['key'] === 'starter'
                && in_array($personaSlug, self::DESIGN_LOCKED_STARTER_PERSONAS, true),
        ]);
    }

    private function block(string $type, array $settings): array
    {
        return ['type' => $type, 'settings' => $settings, 'is_active' => true];
    }

    /**
     * Rich profile card. The `$kit` selects the profile block type
     * (profile_card_v1..v4) and the `identity_*` design variant, whose
     * baked `_style` carries the `_profile_layout`. v3 (Stats) and v4
     * (Badges) get sensible placeholder stats/badges so they render full.
     *
     * @param  array{ptype:string,pvar:string,link:string}  $kit
     * @param  array<string,mixed>  $extra
     */
    private function profile(string $label, string $blurb, string $avatar, array $kit, string $cover = '', array $extra = []): array
    {
        $type = $kit['ptype'];
        $settings = array_merge([
            'name'      => 'Your Name',
            'title'     => $label,
            'avatar'    => $avatar,
            'cover'     => $cover,
            'bio'       => $blurb,
            'verified'  => true,
            'location'  => 'Your City, Country',
            'website'   => 'https://example.com',
            'cta_label' => 'Get in touch',
            'cta_url'   => 'https://example.com',
            'socials'   => $this->profileSocials(),
            '_style'    => $this->variantStyle($type, $kit['pvar']),
        ], $extra);

        if ($type === 'profile_card_v3' && !isset($settings['stats'])) {
            $settings['stats'] = [
                ['label' => 'Followers', 'value' => '12.4K'],
                ['label' => 'Projects',  'value' => '87'],
                ['label' => 'Years',     'value' => '6'],
            ];
        }
        if ($type === 'profile_card_v4' && !isset($settings['badges'])) {
            $settings['badges'] = [
                ['label' => 'Top Rated'],
                ['label' => 'Verified'],
                ['label' => 'Fast Replies'],
            ];
        }

        return $this->block($type, $settings);
    }

    /** @return array<int, array{name:string,url:string}> */
    private function profileSocials(): array
    {
        return [
            ['name' => 'instagram', 'url' => 'https://instagram.com/yourhandle'],
            ['name' => 'tiktok',    'url' => 'https://tiktok.com/@yourhandle'],
            ['name' => 'youtube',   'url' => 'https://youtube.com/@yourhandle'],
            ['name' => 'linkedin',  'url' => 'https://linkedin.com/in/yourhandle'],
        ];
    }

    private function heading(string $text, string $size = 'h3'): array
    {
        return $this->block('heading', ['text' => $text, 'size' => $size, 'align' => 'center']);
    }

    private function paragraph(string $text): array
    {
        return $this->block('paragraph', ['text' => $text, 'align' => 'center']);
    }

    /** @param  array{ptype:string,pvar:string,link:string}|null  $kit */
    private function link(string $text, string $url, string $icon = '', ?array $kit = null): array
    {
        $settings = ['text' => $text, 'url' => $url, 'icon' => $icon];
        if ($kit !== null) {
            $settings['_style'] = $this->variantStyle('link', $kit['link']);
        }
        return $this->block('link', $settings);
    }

    /** @param  array{ptype:string,pvar:string,link:string}|null  $kit */
    private function linkBig(string $text, string $url, string $icon = '', ?array $kit = null): array
    {
        $settings = ['text' => $text, 'url' => $url, 'icon' => $icon];
        if ($kit !== null) {
            $settings['_style'] = $this->variantStyle('link_big', $kit['link']);
        }
        return $this->block('link_big', $settings);
    }

    /** @param  array<int, array{question:string,answer:string}>  $items */
    private function faq(array $items): array
    {
        return $this->block('faq', ['items' => array_values($items)]);
    }

    /** @param  array<int, array{question:string,options:array<int,string>,correct:int}>  $questions */
    private function quiz(string $title, array $questions): array
    {
        return $this->block('quiz', ['title' => $title, 'questions' => array_values($questions)]);
    }

    /** @param  array<int, array{title:string,description:string,date:string}>  $items */
    private function timeline(array $items): array
    {
        return $this->block('timeline', ['items' => array_values($items)]);
    }

    private function product(string $name, string $description, string $price, string $image, string $url, string $badge = ''): array
    {
        return $this->block('product', [
            'name'            => $name,
            'description'     => $description,
            'price'          => $price,
            'image'          => $image,
            'url'            => $url,
            'badge'          => $badge,
            'native_checkout' => false,
        ]);
    }

    private function socials(): array
    {
        // Seed a deterministic set of placeholder platforms so the icon
        // row actually renders in preview. The user replaces these with
        // their own handles after picking the template.
        return $this->block('socials_multi', [
            'groups' => [[
                'label'     => 'Personal',
                'platforms' => [
                    ['name' => 'instagram', 'url' => 'https://instagram.com/yourhandle', 'display' => 'icon'],
                    ['name' => 'tiktok',    'url' => 'https://tiktok.com/@yourhandle',  'display' => 'icon'],
                    ['name' => 'youtube',   'url' => 'https://youtube.com/@yourhandle', 'display' => 'icon'],
                    ['name' => 'twitter',   'url' => 'https://x.com/yourhandle',        'display' => 'icon'],
                    ['name' => 'linkedin',  'url' => 'https://linkedin.com/in/yourhandle', 'display' => 'icon'],
                ],
            ]],
            'size'  => 'md',
            'style' => 'rounded',
        ]);
    }

    private function emailCollector(): array
    {
        return $this->block('email_collector', ['placeholder' => 'you@email.com', 'button_text' => 'Subscribe']);
    }

    private function image(string $url = ''): array
    {
        return $this->block('image', ['url' => $url, 'alt' => '']);
    }

    private function imageGrid(array $images = [], int $columns = 3): array
    {
        return $this->block('image_grid', [
            'columns' => $columns,
            'gap'     => 2,
            'images'  => array_map(fn($u) => ['url' => $u], $images),
        ]);
    }

    private function divider(): array
    {
        return $this->block('divider', []);
    }

    private function list(array $items): array
    {
        return $this->block('list', ['items' => $items]);
    }

    /* ─── new richer blocks ─── */

    private function countdown(string $title, string $relative = '+30 days'): array
    {
        $target = now()->modify($relative)->toIso8601String();
        return $this->block('countdown', ['title' => $title, 'target_date' => $target]);
    }

    private function video(string $url): array
    {
        return $this->block('video', ['url' => $url, 'autoplay' => false]);
    }

    private function testimonials(array $items): array
    {
        return $this->block('testimonials', ['items' => $items]);
    }

    private function review(string $name, int $rating, string $text, string $avatar = ''): array
    {
        return $this->block('review', [
            'name'   => $name,
            'avatar' => $avatar,
            'rating' => $rating,
            'text'   => $text,
        ]);
    }

    private function service(string $name, string $icon, string $price, string $description, string $url): array
    {
        return $this->block('service', [
            'name'        => $name,
            'icon'        => 'fas ' . $icon,
            'price'       => $price,
            'description' => $description,
            'url'         => $url,
        ]);
    }

    private function price(string $title, string $amount, string $period, array $features, string $url): array
    {
        return $this->block('price', [
            'title'    => $title,
            'amount'   => $amount,
            'period'   => $period,
            'features' => $features,
            'url'      => $url,
        ]);
    }

    private function ctaButton(string $text, string $url, string $color = '#3d6bff', string $textColor = '#ffffff', string $size = 'lg'): array
    {
        return $this->block('cta_button', [
            'text'       => $text,
            'url'        => $url,
            'color'      => $color,
            'text_color' => $textColor,
            'size'       => $size,
        ]);
    }

    private function contactForm(string $title, string $buttonText): array
    {
        return $this->block('contact_form', [
            'title'           => $title,
            'button_text'     => $buttonText,
            'success_message' => 'Got it — I\'ll get back to you soon.',
        ]);
    }

    private function poll(string $question, array $options): array
    {
        return $this->block('poll', ['question' => $question, 'options' => array_values($options)]);
    }

    private function qrCode(string $url, int $size = 200): array
    {
        return $this->block('qr_code', ['url' => $url, 'size' => $size]);
    }

    private function donation(string $title, string $description, array $amounts, string $url): array
    {
        return $this->block('donation', [
            'title'       => $title,
            'description' => $description,
            'amounts'     => array_values($amounts),
            'url'         => $url,
        ]);
    }

    private function coupon(string $code, string $description, string $expires): array
    {
        return $this->block('coupon', ['code' => $code, 'description' => $description, 'expires' => $expires]);
    }

    private function vcard(string $name, string $title, string $company, string $phone, string $email, string $website): array
    {
        return $this->block('vcard', [
            'name'    => $name,
            'title'   => $title,
            'company' => $company,
            'phone'   => $phone,
            'email'   => $email,
            'website' => $website,
        ]);
    }

    /**
     * Card container with children — renders a small grid of child blocks
     * inside one styled card. Keeps the variant from devolving back into
     * a plain link list.
     */
    private function cardGrid(string $title, int $columns, array $children): array
    {
        $card = $this->block('card', [
            'title'         => $title,
            'columns'       => $columns,
            'gap'           => 12,
            'padding'       => 16,
            'border_radius' => 16,
            'bg_type'       => 'glass',
            'glass_opacity' => 6,
            'glass_blur'    => 12,
            'shadow'        => 'sm',
        ]);
        $card['children'] = array_values($children);
        return $card;
    }

    /* ──────────────────── realistic demo imagery ──────────────────── */

    /**
     * Persona slug => a LoremFlickr-friendly photo keyword so each
     * persona's templates pull on-topic imagery instead of random
     * placeholders. Visually-concrete slugs (chef, yoga, restaurant…)
     * fall through to the slug itself; only abstract/ambiguous ones are
     * remapped here.
     *
     * @var array<string,string>
     */
    private const PERSONA_IMAGE_KEYWORDS = [
        'creator'    => 'creative,workspace',
        'influencer' => 'lifestyle,social',
        'coach'      => 'coaching,office',
        'business'   => 'business,office',
        'developer'  => 'developer,code',
        'consultant' => 'business,meeting',
        'freelancer' => 'laptop,workspace',
        'agency'     => 'office,team',
        'realestate' => 'realestate,house',
        'nonprofit'  => 'volunteer,community',
        'community'  => 'community,people',
        'student'    => 'study,campus',
        'author'     => 'books,writing',
        'journalist' => 'newsroom,writing',
        'trainer'    => 'gym,training',
        'model'      => 'fashion,model',
        'beauty'     => 'beauty,makeup',
        'event'      => 'event,celebration',
        'other'      => 'minimal,abstract',
    ];

    /** Map a persona slug to a photo keyword (fallback = the slug itself). */
    private function personaKeyword(string $slug): string
    {
        return self::PERSONA_IMAGE_KEYWORDS[$slug] ?? $slug;
    }

    /**
     * Self-hosted placeholder image bundled with the app
     * (public/block-placeholders/*.svg). External photo CDNs (loremflickr)
     * can rate-limit, change, or disappear — which would make seeded template
     * previews look broken over time. Picked by aspect ratio so square slots
     * get the square art and wide banners get the cover art.
     */
    private function photo(string $keywords, int $w, int $h, string $seed): string
    {
        if ($w === $h) {
            return asset('block-placeholders/image-square.svg');
        }
        if ($h > 0 && $w / $h >= 2) {
            return asset('block-placeholders/cover.svg');
        }
        return asset('block-placeholders/image.svg');
    }

    /** Self-hosted avatar placeholder bundled with the app. */
    private function face(string $seed, int $size = 200): string
    {
        return asset('block-placeholders/avatar.svg');
    }

    /* ──────────────────── newer block helpers ──────────────────── */

    /** @param  array<int, array{question:string,answer:string,icon?:string}>  $items */
    private function faqV2(array $items): array
    {
        return $this->block('faq_v2', ['items' => array_values($items)]);
    }

    private function badge(string $text, string $color = '#3d6bff', string $textColor = '#ffffff'): array
    {
        return $this->block('badge', ['text' => $text, 'color' => $color, 'text_color' => $textColor]);
    }

    private function alert(string $text, string $type = 'info', string $icon = 'fa-info-circle'): array
    {
        return $this->block('alert', ['text' => $text, 'type' => $type, 'icon' => $icon]);
    }

    /** @param  array<int, array{label:string,value:int,color?:string}>  $items */
    private function progress(array $items): array
    {
        return $this->block('progress', ['items' => array_values($items)]);
    }

    /** @param  array<int, array{name:string,price:string,included?:bool}>  $items */
    private function listPricing(array $items): array
    {
        return $this->block('list_pricing', ['items' => array_values($items)]);
    }

    private function oneTimeOffer(string $title, string $description, string $price, string $originalPrice, string $url): array
    {
        return $this->block('one_time_offer', [
            'title'          => $title,
            'description'    => $description,
            'price'          => $price,
            'original_price' => $originalPrice,
            'url'            => $url,
        ]);
    }

    /** @param  array<int,string>  $images */
    private function imageSlider(array $images, int $interval = 3500): array
    {
        return $this->block('image_slider', [
            'images'   => array_map(fn($u) => ['url' => $u], array_values($images)),
            'interval' => $interval,
            'effect'   => 'fade',
        ]);
    }

    private function whatsapp(string $phone, string $buttonText = 'Chat on WhatsApp', string $message = ''): array
    {
        return $this->block('whatsapp_widget', [
            'phone'       => $phone,
            'button_text' => $buttonText,
            'message'     => $message,
        ]);
    }
}
