<?php

namespace App\Modules\User\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * A signed-in Zio Dialer app install (task #6353).
 *
 * Recorded at sign-in/unlock independent of push-token registration, so
 * "device linked" no longer requires notification permission. `device_key`
 * is a random per-install identifier generated by the app.
 *
 * @property int $id
 * @property int $user_id
 * @property string $device_key
 * @property string|null $platform
 * @property string|null $device_name
 * @property \Illuminate\Support\Carbon|null $last_seen_at
 */
class DialerDevice extends Model
{
    protected $table = 'dialer_devices';

    protected $fillable = [
        'user_id',
        'device_key',
        'platform',
        'device_name',
        'last_seen_at',
    ];

    protected $casts = [
        'last_seen_at' => 'datetime',
    ];
}
