<?php

namespace App\Modules\User\Support;

use App\Modules\Admin\Models\BgTemplate;

/**
 * REST-shaped catalog of the admin-managed background templates
 * (`bg_templates` table) for the mobile Appearance "Templates" picker —
 * the parity twin of BgPresetCatalog::forApi() for the DB-backed library.
 *
 * React Native can't render the templates' class-based CSS (layered
 * pseudo-elements, animations), so each entry carries:
 *   - `colors`: color stops extracted from the CSS for a LinearGradient
 *     swatch approximation (instant paint + fallback), and
 *   - `swatch`: the public path of a pre-rendered PNG thumbnail of the
 *     REAL CSS texture, generated by the mobile repo's
 *     generate-bg-template-swatches.mjs script. The path is only
 *     advertised when the committed thumbnail was rendered from the
 *     template's current CSS (manifest md5 match keyed by slug) — an
 *     admin editing a template without re-running the generator degrades
 *     that template back to the gradient approximation instead of showing
 *     a stale image.
 */
class BgTemplateCatalog
{
    /** Category labels, mirroring the web appearance picker's chips. */
    public const CATEGORIES = [
        'animated' => 'Animated',
        'gradient' => 'Gradients',
        'mesh'     => 'Mesh',
        'pattern'  => 'Patterns',
        'svg'      => 'SVG',
        'neon'     => 'Neon',
    ];

    /** Public URL path prefix for the pre-rendered swatch thumbnails. */
    private const SWATCH_PUBLIC_PATH = '/img/bg-template-swatches';

    /**
     * @return array{categories: list<array{key: string, label: string}>, templates: list<array{id: int, slug: string, name: string, category: string, colors: list<string>, swatch: string|null}>}
     */
    public static function forApi(): array
    {
        $manifest = self::swatchManifest();

        $templates = [];
        $seenCategories = [];
        foreach (BgTemplate::active()->get() as $tpl) {
            $category = $tpl->category ?: 'pattern';
            $seenCategories[$category] = true;
            $templates[] = [
                'id'       => (int) $tpl->id,
                'slug'     => (string) $tpl->slug,
                'name'     => (string) $tpl->name,
                'category' => $category,
                'colors'   => BgPresetCatalog::swatchStops((string) $tpl->css),
                'swatch'   => ($manifest[$tpl->slug] ?? null) === md5((string) $tpl->css)
                    ? self::SWATCH_PUBLIC_PATH.'/'.$tpl->slug.'.png'
                    : null,
            ];
        }

        // Only advertise categories that actually have templates, in the
        // canonical order; unknown categories (future admin values) are
        // appended so their templates stay reachable.
        $categories = [];
        foreach (self::CATEGORIES as $key => $label) {
            if (isset($seenCategories[$key])) {
                $categories[] = ['key' => $key, 'label' => $label];
                unset($seenCategories[$key]);
            }
        }
        foreach (array_keys($seenCategories) as $key) {
            $categories[] = ['key' => $key, 'label' => ucfirst($key)];
        }

        return ['categories' => $categories, 'templates' => $templates];
    }

    /**
     * slug => md5(css) manifest written alongside the pre-rendered swatch
     * PNGs. Missing/corrupt manifest simply means no thumbnails are
     * advertised (clients fall back to the gradient approximation).
     *
     * @return array<string, string>
     */
    private static function swatchManifest(): array
    {
        static $manifest = null;
        if ($manifest !== null) {
            return $manifest;
        }
        $file = \dirname(__DIR__, 4).'/public'.self::SWATCH_PUBLIC_PATH.'/manifest.json';
        $manifest = [];
        if (is_file($file)) {
            $decoded = json_decode((string) file_get_contents($file), true);
            if (\is_array($decoded)) {
                foreach ($decoded as $k => $v) {
                    if (\is_string($k) && \is_string($v)) {
                        $manifest[$k] = $v;
                    }
                }
            }
        }
        return $manifest;
    }
}
