<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Persistent per-creator AI Brand Kits (Task #2662).
 *
 * Each row is a saved brand identity generated by the AI Brand Kit tool:
 * a color palette, a heading/body font pairing, voice/tone descriptors,
 * tagline options, an about/bio blurb, and a recommended global biolink
 * block theme. All of that structured payload lives in the `config` JSON
 * so the shape can evolve without further migrations; the columns here are
 * just the stable index/ownership surface.
 *
 * Forward-only and guarded so a re-run over the shared RDS is a no-op.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('brand_kits')) {
            return;
        }

        Schema::create('brand_kits', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('name');
            $table->string('slug')->nullable();
            $table->jsonb('config')->default('{}');
            $table->boolean('is_default')->default(false);
            $table->timestamps();

            $table->index(['user_id', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('brand_kits');
    }
};
