<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Registry of signed-in Zio Dialer app installs per user (task #6353).
 *
 * Previously "device linked" meant "has a push token", so installs that
 * denied notification permission (or can't obtain an Expo push token)
 * never counted as linked and the desktop pane pushed the download promo
 * forever. This table records the install itself at sign-in/unlock,
 * independent of push. `device_key` is a random per-install identifier
 * generated by the app; the row is upserted (heartbeat) on every
 * sign-in/unlock and deleted on sign-out.
 */
return new class extends Migration {
    public function up(): void
    {
        if (!Schema::hasTable('dialer_devices')) {
            Schema::create('dialer_devices', function (Blueprint $t) {
                $t->id();
                $t->unsignedBigInteger('user_id')->index();
                // Random per-install key generated by the dialer app.
                $t->string('device_key', 64);
                $t->string('platform', 16)->nullable(); // ios | android | web
                $t->string('device_name')->nullable();
                $t->timestamp('last_seen_at')->nullable();
                $t->timestamps();
                // One row per (user, install); re-registration is a heartbeat.
                $t->unique(['user_id', 'device_key']);
            });
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('dialer_devices');
    }
};
