export interface FaqCategory {
  category: string;
  items: { question: string; answer: string }[];
}

export const faqCategories: FaqCategory[] = [
  {
    category: "Getting started",
    items: [
      { question: "Is there really a free plan?", answer: "Yes — the Free plan is free forever. No trial countdown, no surprise paywall, no credit card required to use it." },
      { question: "Do I need a credit card to sign up?", answer: "No. You can sign up with just an email or phone number and start building a biolink right away." },
      { question: "How long does it take to get my first link live?", answer: "Most people are live in under two minutes — pick a template, drop your socials in, and share the URL." },
      { question: "Can I import my existing Linktree or Beacons page?", answer: "Yes — paste your existing page URL into the importer and we will pull the blocks, icons and links into a starter page you can edit." },
      { question: "Do I need any design skills?", answer: "No. Every block is drag-and-drop with sensible defaults; the templates are professionally designed and fully editable." },
      { question: "What is a \"biolink\" exactly?", answer: "A biolink is a single mobile-first page that holds all your links, content and contact options — perfect for the link slot in your social bios." },
      { question: "Can I have more than one biolink page?", answer: "Yes — make as many as your plan allows. Use one per brand, project or campaign and switch between them in a click." },
      { question: "Will my page work on mobile?", answer: "Yes. Every page is mobile-first, with optional desktop-tuned layouts and per-block visibility for either device." },
      { question: "Can I preview my page before publishing?", answer: "Yes — the live preview updates as you edit, and an unpublished page is only visible to you and your team." },
      { question: "Is 1INME suitable for non-creators?", answer: "Absolutely — it is designed for creators, freelancers, agencies, restaurants, coaches, networking pros and small businesses alike." },
    ],
  },
  {
    category: "Biolinks",
    items: [
      { question: "What blocks can I add?", answer: "Text, images, video, audio, products, donation buttons, social icons, embeds, forms, NFTs, calendars, maps, lead magnets and more." },
      { question: "Can I reorder or hide blocks?", answer: "Yes — drag to reorder, click to hide, or schedule blocks to appear and disappear on specific dates." },
      { question: "Can I sell products?", answer: "Yes — add product blocks with images, pricing, variants, stock and Stripe-powered checkout." },
      { question: "Can I collect tips or donations?", answer: "Yes — add a tip jar block with custom amounts, suggested tiers and an optional thank-you message." },
      { question: "Can I embed a video or playlist?", answer: "Yes — paste a YouTube, Vimeo, Spotify, SoundCloud or Apple Music link and the embed renders inline." },
      { question: "Can I add a contact form?", answer: "Yes — drop in a form block; submissions land in your contacts and can fire emails or webhooks." },
      { question: "Can I add multiple languages?", answer: "Yes — set a default language and add per-block translations; visitors see the version that matches their browser." },
      { question: "Can I theme my biolink?", answer: "Yes — pick from premium themes or override colours, fonts, backgrounds, button shapes and animations." },
      { question: "Can I schedule a launch?", answer: "Yes — schedule a publish date and time, and the page swaps from \"draft\" to \"live\" automatically." },
      { question: "Can I password-protect a page?", answer: "Yes — toggle on a password; visitors must enter it before the page renders." },
    ],
  },
  {
    category: "Short links",
    items: [
      { question: "What is a branded short link?", answer: "A clean URL on your domain (or our default) that redirects to a long destination — repointable any time, no reprinting needed." },
      { question: "Can I use my own domain?", answer: "Yes, on paid plans. Add a CNAME record and your links read https://yourbrand.co/launch instead of the default host." },
      { question: "Can I add UTMs automatically?", answer: "Yes — set per-link or per-domain UTM defaults and we append them on every redirect." },
      { question: "Can I expire a short link?", answer: "Yes — expire by date, by click count, by geo, or rotate to a fallback URL once a cap is hit." },
      { question: "Can I redirect by country/device?", answer: "Yes — add geo, language or device rules and route visitors to different destinations from the same short link." },
      { question: "Can I password-protect?", answer: "Yes — visitors must enter a password before being redirected." },
      { question: "What link types do you support?", answer: "Standard redirects, file downloads, splash pages, iframes, deep links, vCards, calendar files, Wi-Fi credentials and more." },
      { question: "Can I A/B test?", answer: "Yes — define multiple destinations with weights and we will split traffic and measure the winner." },
      { question: "What if a target goes 404?", answer: "We detect broken targets and surface them in your dashboard so you can repoint without breaking shared links." },
      { question: "Are short links rate-limited?", answer: "No — redirects are served from the edge with no per-link click cap on any plan." },
    ],
  },
  {
    category: "QR codes",
    items: [
      { question: "How do I generate a QR code?", answer: "Every link gets a QR code automatically — open the link, switch to the QR tab and download the size you need." },
      { question: "Can I customise the design?", answer: "Yes — colours, dot styles, eye styles, your logo in the centre, and on-brand accent gradients." },
      { question: "What size for print?", answer: "Use the SVG or 1024×1024 PNG for posters; the 512×512 PNG is plenty for stickers and packaging." },
      { question: "Can I change destination after printing?", answer: "Yes — that is the whole point of dynamic QR codes. Re-point the link any time and the printed code keeps working." },
      { question: "Do QR scans count as clicks?", answer: "Yes — scans are tracked separately from web clicks, so you can compare offline vs online performance." },
      { question: "Can a QR open my biolink?", answer: "Yes — generate the QR for your biolink URL and any phone camera will open it instantly." },
      { question: "Do QR codes work without internet?", answer: "The scan does — but the destination needs internet, like any URL." },
      { question: "Can I batch-generate?", answer: "Yes — bulk-create dozens of links and export the QR codes as a zip in your preferred size." },
    ],
  },
  {
    category: "Analytics & AI Coach",
    items: [
      { question: "What do I get on the Free plan?", answer: "Real-time visitor count, geographic breakdown, device, referrer and per-block click-through — for life." },
      { question: "Can I see visits in real time?", answer: "Yes — live visitor pins on a world map show exactly where your audience is right now." },
      { question: "How does the AI Coach work?", answer: "It watches your live numbers, compares against best practice, and surfaces a small prioritised list of one-click fixes." },
      { question: "Can I export analytics?", answer: "Yes — CSV or JSON export of clicks, sessions and conversions, plus a webhook stream for real-time pipelines." },
      { question: "Do you respect Do Not Track?", answer: "Yes — visitors with Do Not Track enabled are counted anonymously without device fingerprints." },
      { question: "Can I track conversions?", answer: "Yes — fire a tracking event from a thank-you page, a webhook, or our JavaScript SDK and conversions show up alongside clicks." },
      { question: "How does it compare to Google Analytics?", answer: "Ours is link-level and visitor-friendly: cookieless by default, no third-party scripts, ready in seconds." },
      { question: "Can I see my best-converting block?", answer: "Yes — every block reports its own clicks, view rate and CTR so you can prune dead weight in seconds." },
      { question: "How long is data retained?", answer: "Forever on paid plans; 12 months on Free. Exports work for the full retention window." },
      { question: "Can I share analytics with a client?", answer: "Yes — generate a read-only share link or invite the client to a workspace as a Viewer." },
    ],
  },
  {
    category: "Team & workspaces",
    items: [
      { question: "What is a workspace?", answer: "A workspace is an isolated container for content, links, contacts and billing. Use one per brand, client or side project." },
      { question: "How many teammates can I add?", answer: "Depends on your plan — Free supports just you, paid plans scale from 3 to unlimited seats." },
      { question: "What roles can I assign?", answer: "Owner, Admin, Editor, Viewer — each maps to a clear set of permissions across pages, links, contacts and billing." },
      { question: "Can I limit teammate visibility?", answer: "Yes — Editors only see content, Viewers only see analytics, and granular permissions can lock down specific actions." },
      { question: "Can I switch workspaces quickly?", answer: "Yes — a switcher in the dashboard top bar jumps between workspaces in one click." },
      { question: "Separate billing per workspace?", answer: "Yes — each workspace has its own plan and invoices, so agencies can bill clients separately." },
      { question: "Can I transfer ownership?", answer: "Yes — Owners can hand off to another Admin from settings; the old Owner becomes an Admin." },
      { question: "Are actions audit-logged?", answer: "Yes — every important change is attributed to the teammate who made it, with a 90-day history on paid plans." },
      { question: "Can I work with freelancers?", answer: "Yes — invite them as a teammate; they get their own account and you can revoke access at any time." },
      { question: "Do teammates count against caps?", answer: "No — limits are per-workspace, not per-seat. Add seats freely without worrying about caps." },
    ],
  },
  {
    category: "Billing & plans",
    items: [
      { question: "Does the Free plan ever expire?", answer: "No — the Free plan is free forever. There is no trial countdown; you can stay on Free as long as you like." },
      { question: "Can I cancel or downgrade?", answer: "Yes — cancel or downgrade any time; you keep your current plan until renewal, then drop to the lower tier." },
      { question: "Do you offer refunds?", answer: "Yes — new paid plan purchases are refundable in full within 7 days, no questions asked." },
      { question: "What payment methods do you accept?", answer: "Major credit/debit cards (Visa, Mastercard, Amex, Discover), Apple Pay, Google Pay and PayPal." },
      { question: "Will I be charged tax?", answer: "Yes, where required by law. Sales tax, VAT or GST is calculated automatically based on billing address." },
      { question: "Are invoices available?", answer: "Yes — every charge generates a downloadable PDF invoice, with company name and VAT/GST id support." },
      { question: "Can I switch monthly to annual?", answer: "Yes — switch any time; we credit the unused portion of your current period." },
      { question: "Are there annual billing discounts?", answer: "Yes — annual plans typically include a 2-month discount versus paying monthly." },
      { question: "Non-profit or student discounts?", answer: "Yes — verified non-profits and students get up to 50% off paid plans." },
      { question: "What if my payment fails?", answer: "We retry a few times; after 7 days of failed retries the workspace downgrades to the Free plan." },
    ],
  },
  {
    category: "Domains & aliases",
    items: [
      { question: "Which domains do I get for free?", answer: "1in.me, bizs.club, getbio.one and Sayzio.app — for free, with no DNS setup." },
      { question: "Can I connect a custom domain?", answer: "On a paid plan, point a CNAME record; we verify automatically and provision a free SSL certificate." },
      { question: "Multiple URLs per link?", answer: "Yes — every link gets a primary slug, and you can add multiple extra aliases that all open the same page." },
      { question: "Branded vs Custom domains?", answer: "Branded are shared/free. Custom is your own domain/subdomain connected via CNAME (paid feature)." },
      { question: "Are aliases available on Free?", answer: "Yes — custom URL aliases are available on every plan, including Free." },
      { question: "Can I see connection health?", answer: "Yes — each custom domain shows its verification status so you always know when it's ready." },
    ],
  },
  {
    category: "Security & privacy",
    items: [
      { question: "Is my data encrypted?", answer: "Yes — TLS 1.3 in transit and AES-256 at rest, with regular external audits." },
      { question: "Do you sell my data?", answer: "No — we never sell personal data and we do not run third-party advertising trackers." },
      { question: "Are you GDPR-compliant?", answer: "Yes — we follow GDPR for EU/EEA and UK GDPR for the UK." },
      { question: "Do you offer a DPA?", answer: "Yes — request our DPA from your account; we counter-sign and return it within a couple of days." },
      { question: "Can I enable 2FA?", answer: "Open security settings and add an authenticator app or SMS." },
      { question: "Where is data stored?", answer: "Primary storage is in the EU with replicated backups in additional regions." },
      { question: "How do I report a security issue?", answer: "Email security@1inme.app; disclosures are eligible for a thank-you bounty." },
      { question: "Can I opt out of analytics?", answer: "Yes — DNT-enabled visitors are counted anonymously, or disable analytics entirely from settings." },
      { question: "What is the backup retention?", answer: "Daily backups are kept for 30 days; weekly snapshots for 90 days." },
      { question: "Is there a status page?", answer: "Yes — a public status page reports current uptime, maintenance and incidents." },
    ],
  },
  {
    category: "Mobile & integrations",
    items: [
      { question: "Is there a mobile app?", answer: "Yes — native iOS and Android apps let you edit pages, scan QR codes, and reply to messages." },
      { question: "Do you have an open API?", answer: "Yes — a documented REST API plus webhooks. Free for any plan that includes API access." },
      { question: "Stripe integration?", answer: "Yes — connect your Stripe account to take payments for products, tips, and donations." },
      { question: "Mailchimp / Klaviyo?", answer: "Yes — sync new contacts and form submissions into either platform with a one-click integration." },
      { question: "Google Sheets?", answer: "Yes — append form submissions or new contacts to a Google Sheet in real time." },
      { question: "Is there a Zapier app?", answer: "Yes — trigger Zaps from any 1INME event and call any 1INME action from a Zap." },
      { question: "Facebook / Google pixels?", answer: "Yes — drop your pixel ID in once and it loads on every page or short link." },
      { question: "Webhooks for clicks?", answer: "Yes — receive a signed payload within seconds of clicks or form submissions." },
      { question: "CRM integration?", answer: "Yes — sync contacts to HubSpot, Pipedrive or Salesforce via native integrations or Zapier." },
      { question: "Can I disable per workspace?", answer: "Yes — each workspace has its own integration settings and credentials." },
    ],
  },
  {
    category: "Audience & referrals",
    items: [
      { question: "How do followers get updates?", answer: "Followers get a clean daily digest email. They can also opt into push notifications." },
      { question: "Can I export my follower list?", answer: "Yes — paid plans get a Top Followers CSV export with engagement stats." },
      { question: "How is this different to a newsletter?", answer: "Newsletter is one channel; followers flow across the digest email, live page, directory, and feed at once." },
      { question: "Can I schedule blocks?", answer: "Yes — every block can have a publish-at and an expire-at date and time." },
      { question: "Are there event reminders?", answer: "Yes — anyone who RSVPs gets an automatic reminder plus a \"add to calendar\" link." },
      { question: "Can I limit RSVPs?", answer: "Yes — set a capacity cap and any further RSVPs roll onto a waitlist." },
      { question: "How do referrals work?", answer: "Pick a code, share your link, and every signup is tracked back to you with reward credit." },
      { question: "Custom referral code?", answer: "Yes — pick any short, memorable code instead of a long URL." },
      { question: "How many social networks can I connect?", answer: "On Free, one of each network. Paid plans unlock multiple accounts per network." },
    ],
  },
];
