{{-- ============================ AI MARKETING STRATEGIST ============================ --}}
@php
    $msUrl = \Illuminate\Support\Facades\Route::has('site.ai-marketing-strategist')
        ? route('site.ai-marketing-strategist')
        : url('/ai-marketing-strategist');

    // Single source of truth for the demo examples (see
    // Common\Support\AiStrategistExamples). The first entry is the resting /
    // no-JS / reduced-motion state rendered as static markup below; the full
    // list is handed to the JS cycle further down.
    $msExamples = $aiStrategistExamples ?? \App\Modules\Common\Support\AiStrategistExamples::all();
    $msEx = $msExamples[0] ?? [];
    $msOrg = $msEx['organic']['items'] ?? [];
    $msPaid = $msEx['paid']['items'] ?? [];
@endphp
<section id="ai-marketing-strategist" class="ms-promo py-24 lg:py-32 relative overflow-hidden">
    <div class="ms-glow ms-glow-a" aria-hidden="true"></div>
    <div class="ms-glow ms-glow-b" aria-hidden="true"></div>
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">

            {{-- Copy --}}
            <div>
                <div class="reveal inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] mb-4 ms-eyebrow">
                    <i class="fas fa-wand-magic-sparkles text-sm"></i> AI Marketing Strategist
                </div>
                <h2 class="reveal rd-1 text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-5">
                    Your marketing plan, <span class="ms-grad">written from your own data.</span>
                </h2>
                <p class="reveal rd-2 text-lg text-gray-400 leading-relaxed mb-8 max-w-xl">
                    Tell it your goal. The strategist reads your real links, analytics and audience,
                    then types out a practical organic + paid plan built around the Sayzio features
                    you already have — with one-click actions you can apply on the spot.
                </p>
                <ul class="reveal rd-3 space-y-3 mb-9 max-w-xl">
                    @foreach ([
                        'Grounded in your real account — never invented metrics',
                        'Organic &amp; paid plans, each play naming the exact feature',
                        'One-click actions you can apply right inside Sayzio',
                        'Refine it by chat, then export and keep every plan',
                    ] as $__mf)
                        <li class="flex items-start gap-3">
                            <span class="ms-check shrink-0"><i class="fas fa-check text-[11px]"></i></span>
                            <span class="text-gray-300">{!! $__mf !!}</span>
                        </li>
                    @endforeach
                </ul>
                <div class="reveal rd-4 flex flex-wrap items-center gap-4">
                    <a href="{{ $msUrl }}" class="ms-btn ms-btn-primary">
                        <i class="fas fa-wand-magic-sparkles"></i> See how it works
                    </a>
                    <button type="button"
                            onclick="window.trackMarketingEvent && window.trackMarketingEvent('landing_home_cta','ai_marketing_strategist'); window.dispatchEvent(new CustomEvent('open-auth',{detail:{tab:'register'}}))"
                            class="ms-btn ms-btn-ghost">
                        Build my strategy free <i class="fas fa-arrow-right text-xs"></i>
                    </button>
                </div>
                <p class="reveal rd-5 text-xs text-gray-500 mt-5">
                    <i class="fas fa-lock-open text-[10px] mr-1 ms-accent-ico"></i>
                    Included on every paid plan · grounded in your data, never invented metrics.
                </p>
            </div>

            {{-- Strategy plan mockup --}}
            <div class="reveal rd-2 ms-card-wrap">
                <div class="ms-card" role="img"
                     aria-label="Example marketing strategy generated by the AI Marketing Strategist for a creator's goal.">
                    <div class="ms-card-bar">
                        <span class="ms-dot" aria-hidden="true"></span>
                        <span class="ms-dot" aria-hidden="true"></span>
                        <span class="ms-dot" aria-hidden="true"></span>
                        <span class="ms-card-title"><span class="ms-live" aria-hidden="true"></span> Sayzio · Marketing Strategist</span>
                    </div>
                    <div class="ms-card-body">
                        <div class="ms-goal-row">
                            <span class="ms-goal-label">Goal</span>
                            <span class="ms-goal-text">{{ $msEx['goal'] ?? '' }}</span><span class="ms-goal-caret" aria-hidden="true">▍</span>
                        </div>

                        <div class="ms-head ms-reveal"><span class="ms-head-mark" aria-hidden="true"></span> <span class="ms-head-text">{{ $msEx['head'] ?? '' }}</span></div>

                        <div class="ms-plan">
                            <div class="ms-plan-tag ms-plan-tag-org ms-reveal">{{ $msEx['organic']['tag'] ?? 'Organic' }}</div>
                            <ul class="ms-plan-list ms-org-list">
                                @foreach ($msOrg as $msItem)
                                    <li class="ms-reveal"><i class="{{ $msItem['icon'] ?? 'fas fa-link' }}"></i> <span class="ms-item-text">{{ $msItem['text'] ?? '' }}</span></li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="ms-plan">
                            <div class="ms-plan-tag ms-plan-tag-paid ms-reveal">{{ $msEx['paid']['tag'] ?? 'Paid' }}</div>
                            <ul class="ms-plan-list ms-paid-list">
                                @foreach ($msPaid as $msItem)
                                    <li class="ms-reveal"><i class="{{ $msItem['icon'] ?? 'fas fa-bullseye' }}"></i> <span class="ms-item-text">{{ $msItem['text'] ?? '' }}</span></li>
                                @endforeach
                            </ul>
                        </div>

                        <div class="ms-kpi ms-reveal"><i class="fas fa-chart-line"></i> KPIs → <span class="ms-kpi-text">{{ $msEx['kpi'] ?? '' }}</span></div>
                    </div>
                </div>
                <div class="ms-badge float-y" style="bottom: -18px; left: -14px;">
                    <span class="ms-badge-ico"><i class="fas fa-bolt text-sm"></i></span>
                    <span>
                        <span class="block text-sm font-semibold ms-badge-title">One-click to apply</span>
                        <span class="block text-xs text-gray-400">Right inside Sayzio</span>
                    </span>
                </div>
            </div>

        </div>
    </div>
</section>

<style>
    /* ===== AI Marketing Strategist promo band ===== */
    .ms-promo { isolation: isolate; --ms: #3d6bff; --ms-soft: #5c83ff; --ms-bright: #90acff; }
    .ms-promo .ms-glow {
        position: absolute; border-radius: 9999px; filter: blur(90px);
        opacity: .22; pointer-events: none; will-change: transform;
    }
    .ms-promo .ms-glow-a { width: 460px; height: 460px; top: -140px; right: -120px; background: #3d6bff; animation: msGlowA 22s ease-in-out infinite; }
    .ms-promo .ms-glow-b { width: 380px; height: 380px; bottom: -160px; left: -100px; background: #5c83ff; opacity: .18; animation: msGlowB 27s ease-in-out infinite; animation-delay: -8s; }
    @keyframes msGlowA { 0%,100% { transform: translate3d(0,0,0) scale(1); } 50% { transform: translate3d(-50px,40px,0) scale(1.12); } }
    @keyframes msGlowB { 0%,100% { transform: translate3d(0,0,0) scale(1); } 50% { transform: translate3d(44px,-36px,0) scale(1.08); } }
    html.light-mode .ms-promo .ms-glow { opacity: .12; }

    .ms-promo .ms-eyebrow { color: var(--ms); }
    .ms-promo .ms-accent-ico { color: var(--ms); }
    .ms-promo .ms-grad {
        background: linear-gradient(100deg, #90acff, #3d6bff, #5c83ff, #90acff);
        background-size: 220% 100%;
        -webkit-background-clip: text; background-clip: text;
        -webkit-text-fill-color: transparent; color: transparent;
        animation: msFlow 7s ease-in-out infinite;
    }
    @keyframes msFlow { 0%,100% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } }

    .ms-promo .ms-check {
        width: 24px; height: 24px; border-radius: 9999px;
        display: inline-flex; align-items: center; justify-content: center;
        color: #fff; background: linear-gradient(135deg, #3d6bff, #5c83ff);
        box-shadow: 0 6px 16px -6px color-mix(in srgb, #3d6bff 70%, transparent);
    }

    .ms-promo .ms-btn {
        display: inline-flex; align-items: center; gap: .5rem;
        padding: .8rem 1.4rem; border-radius: 9999px; font-weight: 700; font-size: .95rem;
        transition: transform .25s ease, box-shadow .3s ease, background .3s ease;
    }
    .ms-promo .ms-btn-primary {
        color: #fff; background: linear-gradient(135deg, #3d6bff, #2342c7);
        box-shadow: 0 18px 40px -16px color-mix(in srgb, #3d6bff 75%, transparent);
    }
    .ms-promo .ms-btn-primary:hover { transform: translateY(-2px); box-shadow: 0 24px 50px -16px color-mix(in srgb, #3d6bff 85%, transparent); }
    .ms-promo .ms-btn-ghost {
        color: var(--ms); border: 1px solid color-mix(in srgb, #3d6bff 45%, transparent);
        background: color-mix(in srgb, #3d6bff 10%, transparent); cursor: pointer;
    }
    .ms-promo .ms-btn-ghost:hover { transform: translateY(-2px); background: color-mix(in srgb, #3d6bff 18%, transparent); }

    /* Strategy card mockup */
    .ms-promo .ms-card-wrap { position: relative; display: flex; justify-content: center; }
    .ms-promo .ms-card {
        width: 100%; max-width: 480px; border-radius: 20px; overflow: hidden;
        border: 1px solid rgba(255,255,255,.10);
        background: linear-gradient(180deg, rgba(13,12,24,.96), rgba(10,10,20,.98));
        box-shadow: 0 40px 90px -40px rgba(61,107,255,.55), 0 14px 36px -14px rgba(0,0,0,.6);
        animation: msBob 7s ease-in-out infinite;
        will-change: transform;
    }
    @keyframes msBob { 0%,100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }
    html.light-mode .ms-promo .ms-card {
        background: linear-gradient(180deg, #0f1326, #0c1020);
        box-shadow: 0 40px 80px -42px rgba(15,23,42,.45), 0 0 0 1px color-mix(in srgb, #3d6bff 22%, transparent);
    }
    .ms-promo .ms-card-bar {
        display: flex; align-items: center; gap: 8px;
        padding: 12px 16px;
        border-bottom: 1px solid rgba(255,255,255,.07);
        background: rgba(255,255,255,.02);
    }
    .ms-promo .ms-dot { width: 11px; height: 11px; border-radius: 9999px; display: inline-block; }
    .ms-promo .ms-dot:nth-child(1) { background: #ff5f57; }
    .ms-promo .ms-dot:nth-child(2) { background: #febc2e; }
    .ms-promo .ms-dot:nth-child(3) { background: #28c840; }
    .ms-promo .ms-card-title {
        margin-left: 8px; font-size: 12px; font-weight: 600; letter-spacing: .02em;
        color: #9ca3af; display: inline-flex; align-items: center; gap: 7px;
    }
    .ms-promo .ms-live {
        width: 7px; height: 7px; border-radius: 9999px; background: #28c840;
        box-shadow: 0 0 0 0 rgba(40,200,64,.6);
        animation: msPulse 2.2s ease-out infinite;
    }
    @keyframes msPulse {
        0%   { box-shadow: 0 0 0 0 rgba(40,200,64,.55); }
        70%  { box-shadow: 0 0 0 7px rgba(40,200,64,0); }
        100% { box-shadow: 0 0 0 0 rgba(40,200,64,0); }
    }
    .ms-promo .ms-card-body {
        padding: 18px 20px 22px;
        font-family: 'Space Grotesk', ui-monospace, SFMono-Regular, Menlo, monospace;
        color: #e5e7eb;
    }
    .ms-promo .ms-goal-row {
        display: flex; flex-wrap: wrap; align-items: baseline; gap: 8px;
        padding-bottom: 14px; margin-bottom: 14px;
        border-bottom: 1px dashed rgba(255,255,255,.10);
    }
    .ms-promo .ms-goal-label {
        font-size: 10px; font-weight: 700; letter-spacing: .14em; text-transform: uppercase;
        color: #fff; background: #3d6bff;
        padding: 3px 8px; border-radius: 7px; flex: 0 0 auto;
    }
    .ms-promo .ms-goal-text { color: #cbd5e1; font-weight: 500; font-size: 13.5px; line-height: 1.5; }
    .ms-promo .ms-goal-caret { opacity: 0; color: var(--ms); font-weight: 400; font-size: 13.5px; }
    .ms-promo .ms-head { color: #fff; font-weight: 700; font-size: 15px; margin-bottom: 14px; display: flex; align-items: center; gap: 8px; }
    .ms-promo .ms-head-mark { width: 9px; height: 9px; border-radius: 2px; background: #3d6bff; display: inline-block; }
    .ms-promo .ms-plan { margin-bottom: 14px; }
    .ms-promo .ms-plan-tag {
        display: inline-block; font-size: 10px; font-weight: 700; letter-spacing: .12em;
        text-transform: uppercase; padding: 3px 9px; border-radius: 7px; margin-bottom: 8px;
    }
    .ms-promo .ms-plan-tag-org { color: #d6e0ff; background: color-mix(in srgb, #3d6bff 22%, transparent); }
    .ms-promo .ms-plan-tag-paid { color: #ffe2c7; background: rgba(255,138,60,.18); }
    .ms-promo .ms-plan-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 6px; }
    .ms-promo .ms-plan-list li { display: flex; align-items: flex-start; gap: 9px; font-size: 13px; line-height: 1.45; color: #cbd5e1; }
    .ms-promo .ms-plan-list i { color: #90acff; margin-top: 3px; width: 15px; text-align: center; flex: 0 0 auto; }
    .ms-promo .ms-kpi {
        margin-top: 16px; padding-top: 14px; border-top: 1px dashed rgba(255,255,255,.10);
        font-size: 12.5px; font-weight: 600; color: #9ff0c4; display: flex; align-items: center; gap: 8px;
    }

    /* Live "writing" reveal — resting / no-JS / reduced-motion = fully visible.
       The stagger-in only kicks in once JS adds `.ms-armed` (never under
       reduced motion), mirroring the AI builder section's fly-in feel. */
    .ms-promo .ms-reveal {
        opacity: 1; transform: none;
        will-change: transform, opacity;
        transition: opacity .5s ease, transform .55s cubic-bezier(.34, 1.56, .64, 1);
    }
    @media (prefers-reduced-motion: no-preference) {
        .ms-promo .ms-card.ms-armed .ms-reveal {
            opacity: 0; transform: translateY(14px) scale(.96);
        }
        .ms-promo .ms-card.ms-armed .ms-reveal.is-in {
            opacity: 1; transform: none;
        }
        /* Blinking caret while the goal types; hidden once typing completes. */
        .ms-promo .ms-card.ms-armed .ms-goal-caret {
            opacity: 1; animation: msCaret 1.05s step-end infinite;
        }
        .ms-promo .ms-card.ms-armed.ms-goal-done .ms-goal-caret {
            opacity: 0; animation: none;
        }
    }
    @keyframes msCaret { 0%, 49% { opacity: 1; } 50%, 100% { opacity: 0; } }

    /* Floating accent badge on the card */
    .ms-promo .ms-badge {
        position: absolute; background: #11101c; border: 1px solid rgba(255,255,255,.10);
        border-radius: 16px; padding: 12px 14px; display: flex; align-items: center; gap: 10px;
        box-shadow: 0 20px 50px -20px rgba(0,0,0,.7);
    }
    html.light-mode .ms-promo .ms-badge { background: #fff; border-color: rgba(15,23,42,.10); }
    .ms-promo .ms-badge-ico {
        width: 36px; height: 36px; border-radius: 12px; flex-shrink: 0;
        display: inline-flex; align-items: center; justify-content: center;
        color: #fff; background: #3d6bff;
    }
    .ms-promo .ms-badge-title { color: #fff; }
    html.light-mode .ms-promo .ms-badge-title { color: #0f172a; }

    @media (prefers-reduced-motion: reduce) {
        .ms-promo .ms-glow,
        .ms-promo .ms-grad,
        .ms-promo .ms-card,
        .ms-promo .ms-live { animation: none !important; }
        .ms-promo .ms-grad {
            background: none !important;
            -webkit-text-fill-color: #90acff !important;
            color: #90acff !important;
        }
    }
</style>

<script>
(function () {
    if (window.__msStrategistInit) return;
    window.__msStrategistInit = true;

    // Example goals the strategist demo cycles through to show its breadth.
    // Sourced from a single server-passed list (Common\Support
    // \AiStrategistExamples) that also drives the resting/no-JS markup above —
    // so the armed sequence picks up seamlessly and adding/removing an example
    // is a one-line data change.
    var EXAMPLES = @json($msExamples ?? []);
    if (!EXAMPLES.length) return;

    function init() {
        var section = document.getElementById('ai-marketing-strategist');
        if (!section) return;
        var card = section.querySelector('.ms-card');
        if (!card) return;

        // Reduced motion / no-JS: leave the card fully assembled (resting state).
        var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        if (reduce) return;

        var goalEl = card.querySelector('.ms-goal-text');
        var headEl = card.querySelector('.ms-head-text');
        var orgTagEl = card.querySelector('.ms-plan-tag-org');
        var paidTagEl = card.querySelector('.ms-plan-tag-paid');
        var kpiEl = card.querySelector('.ms-kpi-text');
        var orgItems = card.querySelectorAll('.ms-org-list li');
        var paidItems = card.querySelectorAll('.ms-paid-list li');
        // Captured once; only the inner text/icons of these rows change per
        // example (the row elements themselves are never recreated), so the
        // NodeList stays valid across cycles.
        var reveals = card.querySelectorAll('.ms-reveal');

        // Paint one example's static content into the (hidden) rows. The goal
        // line is typed separately (see build), so it is cleared here.
        function applyExample(ex) {
            if (headEl) headEl.textContent = ex.head || '';
            if (orgTagEl) orgTagEl.textContent = (ex.organic && ex.organic.tag) || 'Organic';
            if (paidTagEl) paidTagEl.textContent = (ex.paid && ex.paid.tag) || 'Paid';
            if (kpiEl) kpiEl.textContent = ex.kpi || '';

            function fill(rows, items) {
                for (var r = 0; r < rows.length; r++) {
                    var d = items && items[r];
                    if (!d) continue;
                    var ico = rows[r].querySelector('i');
                    var txt = rows[r].querySelector('.ms-item-text');
                    if (ico) ico.className = d.icon || 'fas fa-link';
                    if (txt) txt.textContent = d.text || '';
                }
            }
            fill(orgItems, ex.organic && ex.organic.items);
            fill(paidItems, ex.paid && ex.paid.items);
        }

        // Arm: hide the staggered rows + clear the goal, ready to write live.
        // Done up front so there's no flash of the finished card before play().
        card.classList.add('ms-armed');
        if (goalEl) goalEl.textContent = '';

        var idx = 0;         // which example is on screen
        var visible = false; // section in view
        var running = false; // a write cycle is mid-flight
        var started = false; // first play() has fired
        function after(ms, fn) { return setTimeout(fn, ms); }

        // Run one full "write the plan" cycle for EXAMPLES[idx], then schedule
        // the next example.
        function cycle(isFirst) {
            if (running) return;
            running = true;

            var ex = EXAMPLES[idx];
            var goalText = ex.goal || '';

            function build() {
                applyExample(ex);
                card.classList.remove('ms-goal-done');

                // 1. Type the goal character by character with a blinking caret.
                var i = 0;
                function type() {
                    if (goalEl && i <= goalText.length) {
                        goalEl.textContent = goalText.slice(0, i);
                        i++;
                        after(22 + Math.random() * 34, type);
                    } else {
                        card.classList.add('ms-goal-done'); // stop the caret
                        after(320, reveal);
                    }
                }
                // 2..5. Stagger-reveal heading → Organic tag+items → Paid
                //       tag+items → KPIs, each springing into place.
                function reveal() {
                    var last = 0;
                    reveals.forEach(function (el, ri) {
                        last = 120 + ri * 150;
                        after(last, function () { el.classList.add('is-in'); });
                    });
                    // Hold the finished plan, then hand off to the next example.
                    after(last + 600 + 3200, next);
                }
                type();
            }

            if (isFirst) {
                build();
            } else {
                // Reset to the armed start state, swap content (while hidden),
                // then write the next example out.
                reveals.forEach(function (el) { el.classList.remove('is-in'); });
                card.classList.remove('ms-goal-done');
                if (goalEl) goalEl.textContent = '';
                after(450, build);
            }
        }

        function next() {
            running = false;
            idx = (idx + 1) % EXAMPLES.length;
            if (visible) cycle(false); // keep looping while in view
        }

        function play() {
            if (started) {
                if (!running) cycle(false); // resume after pausing out of view
                return;
            }
            started = true;
            cycle(true);
        }

        if ('IntersectionObserver' in window) {
            var io = new IntersectionObserver(function (entries) {
                entries.forEach(function (e) {
                    visible = e.isIntersecting;
                    if (visible) play();
                });
            }, { threshold: 0.35 });
            io.observe(section);
        } else {
            visible = true;
            play();
        }
    }

    if (document.readyState !== 'loading') init();
    else document.addEventListener('DOMContentLoaded', init);
})();
</script>
